---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-db
spec:
  # We need to be able to update the data stored in this volume periodically from a different
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.resources.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.resources.storageResources }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  arinc.properties: |
    arinc.watchDirectory={{ .Values.arinc.watchDirectory }}
    arinc.filePattern={{ .Values.arinc.filePattern }}