---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: rest-port
      protocol: TCP
      port: 8080
      targetPort: 8080