---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
  {{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
  {{- end}}
  annotations:
  {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end}}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: rest-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080