---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  revisionHistoryLimit: 0
  {{- if .Values.resources.replicas }}
  replicas: {{ .Values.resources.replicas }}
  {{- end}}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      {{- if .Values.deployment.annotations }}
      annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          {{- if .Values.deployment.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.deployment.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.deployment.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.deployment.readinessProbe | indent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
          env:
            - name: arinc.config.properties
              value: /config/arinc.properties
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memoryLimit }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: {{ .Values.name }}-db
              mountPath: {{ .Values.arinc.watchDirectory }}
              readOnly: false
        {{- if .Values.arinc.image }}
        - name: {{ .Values.name }}-arinc
          image: {{ .Values.arinc.image }}
          imagePullPolicy: Always
          env:
            - name: ARINC_PATH
              value: {{ .Values.arinc.watchDirectory }}
          volumeMounts:
            - name: {{.Values.name}}-db
              mountPath: {{.Values.arinc.watchDirectory }}
              readOnly: false
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-config
            items:
              - key: arinc.properties
                path: arinc.properties
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.name }}-db
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: {{ .Values.resources.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.resources.storageResources }}