package org.mitre.tdp.boogie.dafif;

import java.util.List;

import org.mitre.tdp.boogie.dafif.model.DafifAddRunway;
import org.mitre.tdp.boogie.dafif.model.DafifAirport;
import org.mitre.tdp.boogie.dafif.model.DafifIls;
import org.mitre.tdp.boogie.dafif.model.DafifNavaid;
import org.mitre.tdp.boogie.dafif.model.DafifRunway;
import org.mitre.tdp.boogie.dafif.model.DafifTerminalParent;
import org.mitre.tdp.boogie.dafif.model.DafifTerminalSegment;
import org.mitre.tdp.boogie.dafif.model.DafifWaypoint;

public class TestObjects {

  public static final DafifNavaid aa = DafifNavaid.builder()
      .navaidIdentifier("AA")
      .navaidKeyCode(0)
      .countryCode("UI")
      .navaidType(5)
      .navaidSlavedVariation(null)
      .cycleDate(201907)
      .degreesLatitude(47.009053)
      .degreesLongitude(-96.815183)
      .build();

  public static final DafifNavaid abr = DafifNavaid.builder()
      .navaidIdentifier("ABR")
      .navaidType(4)
      .navaidKeyCode(0)
      .navaidSlavedVariation("E00700188")
      .cycleDate(202110)
      .degreesLatitude(45.417356)
      .degreesLongitude(-98.368719)
      .build();

  public static final DafifWaypoint fakeAA = DafifWaypoint.builder()
      .waypointIdentifier("N12345")
      .countryCode("UI")
      .waypointType("NR")
      .navaidKeyCode(0)
      .navaidType(5)
      .navaidCountryCode("UI")
      .navaidIdentifier("AA")
      .waypointPointNavaidFlag(true)
      .degreesLatitude(47.009053)
      .degreesLongitude(-96.815183)
      .cycleDate(201907)
      .build();

  public static final DafifAirport fakeAirport = DafifAirport.builder()
      .airportIdentification("FAKE1")
      .icaoCode("IDK1")
      .faaHostCountryIdentifier("AAA")
      .cycleDate(202301)
      .degreesLatitude(12.35)
      .degreesLongitude(23.34)
      .magVarOfRecord("E002065")
      .cycleDate(202110)
      .build();

  public static final DafifAirport fakeAirport2 = DafifAirport.builder()
      .airportIdentification("FAKE2")
      .icaoCode("IDK2")
      .faaHostCountryIdentifier("AAA")
      .cycleDate(202404)
      .degreesLatitude(35.1274)
      .degreesLongitude(-80.9419)
      .magVarOfRecord("W003020")
      .build();

  public static final DafifAirport fakeAirport3 = DafifAirport.builder()
      .airportIdentification("FAKE3")
      .icaoCode("IDK3")
      .faaHostCountryIdentifier("AAA")
      .cycleDate(202404)
      .degreesLatitude(44.9821)
      .degreesLongitude(-93.2731)
      .magVarOfRecord("W001045")
      .build();

  public static final DafifRunway rwy1129 = DafifRunway.builder()
      .lowEndIdentifier("11")
      .highEndIdentifier("29")
      .airportIdentification("FAKE1")
      .highEndMagneticHeading(295.2)
      .lowEndMagneticHeading(115.1)
      .length(9310)
      .width(152)
      .surface("ASP")
      .pavementClassificationNumber("071FAWT")
      .highEndGeodeticLatitude("N12305415")
      .highEndDegreesLatitude(12.508132)
      .highEndGeodeticLongitude("W070002137")
      .highEndDegreesLongitude(-70.018742)
      .highEndElevation("69")
      .highEndSlope("-0.4")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(95)
      .highEndDisplacedThresholdElevation("69")
      .highEndLightingSystem(List.of(12, 6, 49))
      .lowEndGeodeticLatitude("N12311655")
      .lowEndDegreesLatitude(12.514902)
      .lowEndGeodeticLongitude("W070013827")
      .lowEndDegreesLongitude(-70.024611)
      .lowEndElevation("18")
      .lowEndSlope("0.4")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(260)
      .lowEndDisplacedThresholdElevation("18")
      .lowEndLightingSystem(List.of(12, 6, 49))
      .trueHeadingHighEnd(284.2)
      .trueHeadingLowEnd(104.0)
      .highEndLandingDistance(8960)
      .highEndRunwayDistance(9040)
      .highEndTakeOffDistance(9040)
      .highEndAccelerateStopDistance(9040)
      .lowEndLandingDistance(8960)
      .lowEndRunwayDistance(9230)
      .lowEndTakeOffDistance(9230)
      .lowEndAccelerateStopDistance(9230)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifRunway rwy0523 = DafifRunway.builder()
      .lowEndIdentifier("05")
      .highEndIdentifier("23")
      .airportIdentification("FAKE2")
      .highEndMagneticHeading(234.8)
      .lowEndMagneticHeading(54.9)
      .length(7820)
      .width(150)
      .surface("CON")
      .pavementClassificationNumber("055FBCN")
      .highEndGeodeticLatitude("N35124460")
      .highEndDegreesLatitude(35.212667)
      .highEndGeodeticLongitude("W080565200")
      .highEndDegreesLongitude(-80.947222)
      .highEndElevation("745")
      .highEndSlope("0.2")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(120)
      .highEndDisplacedThresholdElevation("746")
      .highEndLightingSystem(List.of(3, 21))
      .lowEndGeodeticLatitude("N35123610")
      .lowEndDegreesLatitude(35.210028)
      .lowEndGeodeticLongitude("W080563520")
      .lowEndDegreesLongitude(-80.942278)
      .lowEndElevation("732")
      .lowEndSlope("-0.2")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(85)
      .lowEndDisplacedThresholdElevation("733")
      .lowEndLightingSystem(List.of(3, 21))
      .trueHeadingHighEnd(235.3)
      .trueHeadingLowEnd(55.2)
      .highEndLandingDistance(7500)
      .highEndRunwayDistance(7820)
      .highEndTakeOffDistance(7820)
      .highEndAccelerateStopDistance(7820)
      .lowEndLandingDistance(7400)
      .lowEndRunwayDistance(7820)
      .lowEndTakeOffDistance(7900)
      .lowEndAccelerateStopDistance(7820)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifRunway rwy0918 = DafifRunway.builder()
      .lowEndIdentifier("09")
      .highEndIdentifier("18")
      .airportIdentification("FAKE3")
      .highEndMagneticHeading(184.0)
      .lowEndMagneticHeading(4.1)
      .length(6100)
      .width(100)
      .surface("ASP")
      .pavementClassificationNumber("040FBDT")
      .highEndGeodeticLatitude("N44585410")
      .highEndDegreesLatitude(44.981694)
      .highEndGeodeticLongitude("W093163800")
      .highEndDegreesLongitude(-93.276667)
      .highEndElevation("840")
      .highEndSlope("0.0")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(60)
      .highEndDisplacedThresholdElevation("840")
      .highEndLightingSystem(List.of(12, 7))
      .lowEndGeodeticLatitude("N44590030")
      .lowEndDegreesLatitude(44.983417)
      .lowEndGeodeticLongitude("W093163450")
      .lowEndDegreesLongitude(-93.279167)
      .lowEndElevation("846")
      .lowEndSlope("0.1")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(35)
      .lowEndDisplacedThresholdElevation("846")
      .lowEndLightingSystem(List.of(12, 7))
      .trueHeadingHighEnd(184.6)
      .trueHeadingLowEnd(4.7)
      .highEndLandingDistance(6000)
      .highEndRunwayDistance(6100)
      .highEndTakeOffDistance(6100)
      .highEndAccelerateStopDistance(6100)
      .lowEndLandingDistance(5950)
      .lowEndRunwayDistance(6100)
      .lowEndTakeOffDistance(6150)
      .lowEndAccelerateStopDistance(6100)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifRunway rwy0220 = DafifRunway.builder()
      .lowEndIdentifier("02")
      .highEndIdentifier("20")
      .airportIdentification("FAKE1")
      .highEndMagneticHeading(204.7)
      .lowEndMagneticHeading(24.9)
      .length(5400)
      .width(100)
      .surface("GRS")
      .pavementClassificationNumber("020FBGR")
      .highEndGeodeticLatitude("N12310010")
      .highEndDegreesLatitude(12.516694)
      .highEndGeodeticLongitude("W070010900")
      .highEndDegreesLongitude(-70.180556)
      .highEndElevation("52")
      .highEndSlope("0.3")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(0)
      .highEndDisplacedThresholdElevation("52")
      .highEndLightingSystem(List.of(0))
      .lowEndGeodeticLatitude("N12310780")
      .lowEndDegreesLatitude(12.518833)
      .lowEndGeodeticLongitude("W070010060")
      .lowEndDegreesLongitude(-70.167222)
      .lowEndElevation("58")
      .lowEndSlope("-0.3")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(0)
      .lowEndDisplacedThresholdElevation("58")
      .lowEndLightingSystem(List.of(0))
      .trueHeadingHighEnd(205.3)
      .trueHeadingLowEnd(25.4)
      .highEndLandingDistance(5300)
      .highEndRunwayDistance(5400)
      .highEndTakeOffDistance(5400)
      .highEndAccelerateStopDistance(5400)
      .lowEndLandingDistance(5200)
      .lowEndRunwayDistance(5400)
      .lowEndTakeOffDistance(5450)
      .lowEndAccelerateStopDistance(5400)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifAddRunway addRunway = DafifAddRunway.builder()
      .airportIdentification("FAKE1")
      .highEndRunwayIdentifier("29")
      .lowEndRunwayIdentifier("11")
      .icaoCode("IDK1")
      .highEndDisplacedThresholdGeodeticLatitude("N12295464")
      .highEndDisplacedThresholdDegreesLatitude(12.498511)
      .highEndDisplacedThresholdGeodeticLongitude("W070001147")
      .highEndDisplacedThresholdDegreesLongitude(-70.003186)
      .highEndOverrunDistance(186)
      .highEndOverrunSurface("ASP")
      .highEndOverrunGeodeticLatitude("N12301657")
      .highEndOverrunDegreesLatitude(12.504604)
      .highEndOverrunGeodeticLongitude("W070014349")
      .highEndOverrunDegreesLongitude(-70.028749)
      .lowEndDisplacedThresholdGeodeticLatitude("N12301550")
      .lowEndDisplacedThresholdDegreesLatitude(12.504306)
      .lowEndDisplacedThresholdGeodeticLongitude("W070013897")
      .lowEndDisplacedThresholdDegreesLongitude(-70.027492)
      .lowEndOverrunSurface("U")
      .cycleDate(202403)
      .build();

  public static final DafifAddRunway addRunway0523 = DafifAddRunway.builder()
      .airportIdentification("FAKE2")
      .highEndRunwayIdentifier("23")
      .lowEndRunwayIdentifier("05")
      .icaoCode("IDK2")
      .highEndDisplacedThresholdGeodeticLatitude("N35124380")
      .highEndDisplacedThresholdDegreesLatitude(35.212167)
      .highEndDisplacedThresholdGeodeticLongitude("W080565470")
      .highEndDisplacedThresholdDegreesLongitude(-80.946389)
      .highEndOverrunDistance(220)
      .highEndOverrunSurface("CON")
      .highEndOverrunGeodeticLatitude("N35124320")
      .highEndOverrunDegreesLatitude(35.211833)
      .highEndOverrunGeodeticLongitude("W080565750")
      .highEndOverrunDegreesLongitude(-80.945556)
      .lowEndDisplacedThresholdGeodeticLatitude("N35123670")
      .lowEndDisplacedThresholdDegreesLatitude(35.210417)
      .lowEndDisplacedThresholdGeodeticLongitude("W080563240")
      .lowEndDisplacedThresholdDegreesLongitude(-80.943000)
      .lowEndOverrunDistance(180)
      .lowEndOverrunSurface("ASP")
      .lowEndOverrunGeodeticLatitude("N35123620")
      .lowEndOverrunDegreesLatitude(35.210111)
      .lowEndOverrunGeodeticLongitude("W080562980")
      .lowEndOverrunDegreesLongitude(-80.942222)
      .cycleDate(202404)
      .build();

  public static final DafifAddRunway addRunway0918 = DafifAddRunway.builder()
      .airportIdentification("FAKE3")
      .highEndRunwayIdentifier("18")
      .lowEndRunwayIdentifier("09")
      .icaoCode("IDK3")
      .highEndDisplacedThresholdGeodeticLatitude("N44585360")
      .highEndDisplacedThresholdDegreesLatitude(44.981333)
      .highEndDisplacedThresholdGeodeticLongitude("W093163860")
      .highEndDisplacedThresholdDegreesLongitude(-93.277000)
      .highEndOverrunDistance(120)
      .highEndOverrunSurface("ASP")
      .highEndOverrunGeodeticLatitude("N44585320")
      .highEndOverrunDegreesLatitude(44.981111)
      .highEndOverrunGeodeticLongitude("W093163950")
      .highEndOverrunDegreesLongitude(-93.277500)
      .lowEndDisplacedThresholdGeodeticLatitude("N44590000")
      .lowEndDisplacedThresholdDegreesLatitude(44.983333)
      .lowEndDisplacedThresholdGeodeticLongitude("W093163420")
      .lowEndDisplacedThresholdDegreesLongitude(-93.279000)
      .lowEndOverrunDistance(90)
      .lowEndOverrunSurface("GRS")
      .lowEndOverrunGeodeticLatitude("N44590040")
      .lowEndOverrunDegreesLatitude(44.983556)
      .lowEndOverrunGeodeticLongitude("W093163380")
      .lowEndOverrunDegreesLongitude(-93.279278)
      .cycleDate(202404)
      .build();

  public static final DafifNavaid fakeVOR = DafifNavaid.builder()
      .navaidIdentifier("FVR")
      .countryCode("UI")
      .navaidKeyCode(0)
      .navaidType(4)
      .navaidSlavedVariation("W00200310")
      .cycleDate(202404)
      .degreesLatitude(35.1203)
      .degreesLongitude(-80.9522)
      .build();

  public static final DafifWaypoint bober = DafifWaypoint.builder()
      .waypointIdentifier("BOBER")
      .countryCode("UI")
      .waypointType("NR")
      .waypointPointNavaidFlag(false)
      .degreesLatitude(47.009053)
      .degreesLongitude(-96.815183)
      .cycleDate(201907)
      .build();

  public static final DafifWaypoint fakeWaypointVorCollocated = DafifWaypoint.builder()
      .waypointIdentifier("FVR")
      .countryCode("UI")
      .waypointType("NR")
      .waypointPointNavaidFlag(false)
      .degreesLatitude(35.1203)
      .degreesLongitude(-80.9522)
      .cycleDate(202404)
      .build();

  public static final DafifWaypoint fakeFix = DafifWaypoint.builder()
      .waypointIdentifier("FIX01")
      .countryCode("UI")
      .waypointType("EN")
      .waypointPointNavaidFlag(false)
      .degreesLatitude(35.1302)
      .degreesLongitude(-80.9306)
      .cycleDate(202404)
      .build();

  public static final DafifWaypoint wptAdrivAA = DafifWaypoint.builder()
      .waypointIdentifier("ADRIV")
      .countryCode("AA")
      .waypointType("R")
      .waypointPointNavaidFlag(false)
      .waypointDescriptionName("ADRIV")
      .icaoCode("TNCF")
      .waypointUsageCode("L")
      .wac("0707")
      .localHorizontalDatum("WGE")
      .geodeticDatum("WGE")
      .geodeticLatitude("N12234179")
      .degreesLatitude(12.395042)
      .geodeticLongitude("W069361217")
      .degreesLongitude(-69.603281)
      .magneticVariation(-11.395)
      .cycleDate(202106)
      .coordinatePrecision(0)
      .build();

  public static final DafifWaypoint wptCa400AA = DafifWaypoint.builder()
      .waypointIdentifier("CA400")
      .countryCode("AA")
      .waypointType("R")
      .waypointPointNavaidFlag(false)
      .waypointDescriptionName("CA400")
      .icaoCode("TNCA")
      .waypointUsageCode("L")
      .localHorizontalDatum("WGE")
      .geodeticDatum("WGE")
      .geodeticLatitude("N12255604")
      .degreesLatitude(12.432333)
      .geodeticLongitude("W069442541")
      .degreesLongitude(-69.740292)
      .magneticVariation(-11.582)
      .cycleDate(201907)
      .coordinatePrecision(0)
      .build();

  public static final DafifWaypoint wptMidvuAA = DafifWaypoint.builder()
      .waypointIdentifier("MIDVU")
      .countryCode("AA")
      .waypointType("R")
      .waypointPointNavaidFlag(false)
      .waypointDescriptionName("MIDVU")
      .icaoCode("TNCA")
      .waypointUsageCode("L")
      .localHorizontalDatum("WGE")
      .geodeticDatum("WGE")
      .geodeticLatitude("N12271909")
      .degreesLatitude(12.455503)
      .geodeticLongitude("W069492015")
      .degreesLongitude(-69.822064)
      .magneticVariation(-11.539)
      .cycleDate(201907)
      .coordinatePrecision(0)
      .build();

  public static final DafifWaypoint wptAndopAS = DafifWaypoint.builder()
      .waypointIdentifier("ANDOP")
      .countryCode("AS")
      .waypointType("R")
      .waypointPointNavaidFlag(false)
      .waypointDescriptionName("ANDOP")
      .icaoCode("YBBB")
      .waypointUsageCode("H")
      .wac("1219")
      .localHorizontalDatum("WGE")
      .geodeticDatum("WGE")
      .geodeticLatitude("S16282680")
      .degreesLatitude(-16.474211)
      .geodeticLongitude("E144580690")
      .degreesLongitude(144.968483)
      .magneticVariation(6.300)
      .cycleDate(202312)
      .coordinatePrecision(0)
      .build();

  public static final DafifWaypoint wptCodieAS = DafifWaypoint.builder()
      .waypointIdentifier("CODIE")
      .countryCode("AS")
      .waypointType("R")
      .waypointPointNavaidFlag(false)
      .waypointDescriptionName("CODIE")
      .icaoCode("YBCS")
      .waypointUsageCode("H")
      .localHorizontalDatum("WGE")
      .geodeticDatum("WGE")
      .geodeticLatitude("S16324200")
      .degreesLatitude(-16.545200)
      .geodeticLongitude("E145355400")
      .degreesLongitude(145.598133)
      .magneticVariation(6.482)
      .cycleDate(202312)
      .coordinatePrecision(0)
      .build();

  public static final  DafifIls fakeIls = DafifIls.builder()
      .runwayIdentifier("11")
      .airportIdentification("FAKE1")
      .ilsNavaidIdentifier("I234")
      .countryCode("AAA")
      .cycleDate(202110)
      .degreesLatitude(12.32)
      .degreesLongitude(23.32)
      .build();

  public static final DafifIls fakeIls05 = DafifIls.builder()
      .runwayIdentifier("05")
      .airportIdentification("FAKE2")
      .ilsNavaidIdentifier("IF05")
      .countryCode("AAA")
      .cycleDate(202404)
      .degreesLatitude(35.2112)
      .degreesLongitude(-80.9441)
      .build();

  public static final DafifIls fakeIls09 = DafifIls.builder()
      .runwayIdentifier("09")
      .airportIdentification("FAKE3")
      .ilsNavaidIdentifier("IF09")
      .countryCode("AAA")
      .cycleDate(202404)
      .degreesLatitude(44.9831)
      .degreesLongitude(-93.2782)
      .build();

  public static final DafifAirport arptAA30079 = DafifAirport.builder()
      .airportIdentification("AA30079")
      .name("QUEEN BEATRIX INTL")
      .icaoCode("TNCA")
      .faaHostCountryIdentifier("N")
      .localHorizontalDatum("WGE")
      .geodeticDatum("WGE")
      .geodeticLatitude("N12300529")
      .degreesLatitude(12.502)
      .geodeticLongitude("W070005618")
      .degreesLongitude(-70.016)
      .elevation(65)
      .airportType("A")
      .mageneticVariation("W011250 0124")
      .wac("0707")
      .beacon("Y")
      .primaryOperatingAgency("CI")
      .cycleDate(202405)
      .coordinatePrecision(0)
      .magVarOfRecord("W011025")
      .build();

  public static final DafifAirport arptAS10286 = DafifAirport.builder()
      .airportIdentification("AS10286")
      .name("CAIRNS INTERNATIONAL")
      .icaoCode("YBCS")
      .faaHostCountryIdentifier("N")
      .localHorizontalDatum("WGE")
      .geodeticDatum("WGE")
      .geodeticLatitude("S16524476")
      .degreesLatitude(-16.880)
      .geodeticLongitude("E145445854")
      .degreesLongitude(145.750)
      .elevation(12)
      .airportType("A")
      .mageneticVariation("E006350 0124")
      .wac("1219")
      .beacon("Y")
      .primaryOperatingAgency("CI")
      .cycleDate(202308)
      .coordinatePrecision(0)
      .magVarOfRecord("E007020")
      .build();

  public static final DafifRunway rwyAA30079_2911 = DafifRunway.builder()
      .airportIdentification("AA30079")
      .highEndIdentifier("29")
      .lowEndIdentifier("11")
      .highEndMagneticHeading(294.5)
      .lowEndMagneticHeading(114.5)
      .length(9280)
      .width(150)
      .surface("ASP")
      .pavementClassificationNumber("070FAWT")
      .highEndGeodeticLatitude("N12295445")
      .highEndDegreesLatitude(12.498458)
      .highEndGeodeticLongitude("W070001068")
      .highEndDegreesLongitude(-70.002967)
      .highEndElevation("64")
      .highEndSlope("-0.5")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(85)
      .highEndDisplacedThresholdElevation("64")
      .highEndLightingSystem(List.of(12, 5, 50))
      .lowEndGeodeticLatitude("N12301614")
      .lowEndDegreesLatitude(12.504483)
      .lowEndGeodeticLongitude("W070014168")
      .lowEndDegreesLongitude(-70.028244)
      .lowEndElevation("14")
      .lowEndSlope("0.5")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(280)
      .lowEndDisplacedThresholdElevation("14")
      .lowEndLightingSystem(List.of(12, 5, 50))
      .trueHeadingHighEnd(283.8)
      .trueHeadingLowEnd(103.8)
      .highEndLandingDistance(8925)
      .highEndRunwayDistance(9010)
      .highEndTakeOffDistance(9010)
      .highEndAccelerateStopDistance(9010)
      .lowEndLandingDistance(8925)
      .lowEndRunwayDistance(9200)
      .lowEndTakeOffDistance(9200)
      .lowEndAccelerateStopDistance(9200)
      .cycleDate(202109)
      .coordinatePrecision(0)
      .build();

  public static final DafifRunway rwyAS10286_3315 = DafifRunway.builder()
      .airportIdentification("AS10286")
      .highEndIdentifier("33")
      .lowEndIdentifier("15")
      .highEndMagneticHeading(330.2)
      .lowEndMagneticHeading(150.2)
      .length(10490)
      .width(150)
      .surface("ASP")
      .pavementClassificationNumber("112FDXT")
      .highEndGeodeticLatitude("S16533228")
      .highEndDegreesLatitude(-16.892300)
      .highEndGeodeticLongitude("E145451996")
      .highEndDegreesLongitude(145.755544)
      .highEndElevation("10")
      .highEndSlope("0.0")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(135)
      .highEndDisplacedThresholdElevation("10")
      .highEndLightingSystem(List.of(5, 50))
      .lowEndGeodeticLatitude("S16515694")
      .lowEndDegreesLatitude(-16.865817)
      .lowEndGeodeticLongitude("E145443685")
      .lowEndDegreesLongitude(145.743569)
      .lowEndElevation("11")
      .lowEndSlope("0.0")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(0)
      .lowEndDisplacedThresholdElevation("U")
      .lowEndLightingSystem(List.of(33, 5, 50))
      .trueHeadingHighEnd(336.2)
      .trueHeadingLowEnd(156.2)
      .highEndLandingDistance(10360)
      .highEndRunwayDistance(10490)
      .highEndTakeOffDistance(10690)
      .highEndAccelerateStopDistance(10490)
      .lowEndLandingDistance(10360)
      .lowEndRunwayDistance(10360)
      .lowEndTakeOffDistance(10690)
      .lowEndAccelerateStopDistance(10360)
      .cycleDate(202308)
      .coordinatePrecision(0)
      .build();

  public static final DafifTerminalParent trmParAA30079Adri1C = new DafifTerminalParent.Builder()
      .airportIdentification("AA30079")
      .terminalProcedureType(1)
      .terminalIdentifier("ADRI1C ADRIV 1C (RNAV)")
      .icaoCode("TNCA")
      .julianDate(2021335)
      .amendmentNumber("3")
      .officeOfPrimaryResponsibility("USN")
      .hostCountryAuthority("CIV")
      .cycleDate(202111)
      .transitionAltitude(2600)
      .transitionLevel(3900)
      .procedureDesignCriteria("PANS-OPS")
      .procedureAmendmentDate("03DEC21")
      .levelOfService1("N")
      .levelOfService2("N")
      .levelOfService3("N")
      .procedureDesignMagvar("W011025")
      .build();

  public static final List<DafifTerminalSegment> trmSegAA30079Adri1CRw29 = List.of(
      new DafifTerminalSegment.Builder()
          .airportIdentification("AA30079")
          .terminalProcedureType(1)
          .terminalIdentifier("ADRI1C ADRIV 1C (RNAV)")
          .terminalSequenceNumber(10)
          .terminalApproachType("5")
          .transitionIdentifier("RW29")
          .icaoCode("TNCA")
          .trackDescriptionCode("IF")
          .termSegWaypointIdentifier("ADRIV")
          .waypointCountryCode("AA")
          .terminalWaypointDescriptionCode1("E")
          .altitudeDescription("+")
          .altitude1("04500")
          .cycleDate(201708)
          .waypointGeodeticLatitude("N12234179")
          .waypointDegreesLatitude(12.395042)
          .waypointGeodeticLongitude("W069361217")
          .waypointDegreesLongitude(-69.603281)
          .waypointMagneticVariation(-11.652600)
          .build(),
      new DafifTerminalSegment.Builder()
          .airportIdentification("AA30079")
          .terminalProcedureType(1)
          .terminalIdentifier("ADRI1C ADRIV 1C (RNAV)")
          .terminalSequenceNumber(20)
          .terminalApproachType("5")
          .transitionIdentifier("RW29")
          .icaoCode("TNCA")
          .trackDescriptionCode("TF")
          .termSegWaypointIdentifier("CA400")
          .waypointCountryCode("AA")
          .terminalWaypointDescriptionCode1("E")
          .altitudeDescription("+")
          .altitude1("04500")
          .cycleDate(201907)
          .waypointGeodeticLatitude("N12255604")
          .waypointDegreesLatitude(12.432333)
          .waypointGeodeticLongitude("W069442541")
          .waypointDegreesLongitude(-69.740292)
          .waypointMagneticVariation(-11.581650)
          .build(),
      new DafifTerminalSegment.Builder()
          .airportIdentification("AA30079")
          .terminalProcedureType(1)
          .terminalIdentifier("ADRI1C ADRIV 1C (RNAV)")
          .terminalSequenceNumber(30)
          .terminalApproachType("5")
          .transitionIdentifier("RW29")
          .icaoCode("TNCA")
          .trackDescriptionCode("TF")
          .termSegWaypointIdentifier("MIDVU")
          .waypointCountryCode("AA")
          .terminalWaypointDescriptionCode1("E")
          .terminalWaypointDescriptionCode2("E")
          .terminalWaypointDescriptionCode4("H")
          .altitudeDescription("+")
          .altitude1("02600")
          .cycleDate(201907)
          .waypointGeodeticLatitude("N12271909")
          .waypointDegreesLatitude(12.455503)
          .waypointGeodeticLongitude("W069492015")
          .waypointDegreesLongitude(-69.822064)
          .waypointMagneticVariation(-11.539180)
          .build()
  );

  public static final DafifTerminalParent trmParAS10286Codi8A = new DafifTerminalParent.Builder()
      .airportIdentification("AS10286")
      .terminalProcedureType(1)
      .terminalIdentifier("CODI8A CODIE 8A (RNAV)")
      .icaoCode("YBCS")
      .julianDate(2023334)
      .amendmentNumber("9")
      .officeOfPrimaryResponsibility("NGA")
      .hostCountryAuthority("CIV")
      .cycleDate(202312)
      .transitionAltitude(10100)
      .procedureDesignCriteria("PANS-OPS")
      .procedureAmendmentDate("01DEC23")
      .levelOfService1("N")
      .levelOfService2("N")
      .levelOfService3("N")
      .procedureDesignMagvar("E007060")
      .build();

  public static final List<DafifTerminalSegment> trmSegAS10286Codi8AAndop = List.of(
      new DafifTerminalSegment.Builder()
          .airportIdentification("AS10286")
          .terminalProcedureType(1)
          .terminalIdentifier("CODI8A CODIE 8A (RNAV)")
          .terminalSequenceNumber(10)
          .terminalApproachType("4")
          .transitionIdentifier("ANDOP")
          .icaoCode("YBCS")
          .trackDescriptionCode("IF")
          .termSegWaypointIdentifier("ANDOP")
          .waypointCountryCode("AS")
          .terminalWaypointDescriptionCode1("E")
          .cycleDate(202312)
          .waypointGeodeticLatitude("S16282680")
          .waypointDegreesLatitude(-16.474211)
          .waypointGeodeticLongitude("E144580690")
          .waypointDegreesLongitude(144.968483)
          .waypointMagneticVariation(6.299880)
          .build(),
      new DafifTerminalSegment.Builder()
          .airportIdentification("AS10286")
          .terminalProcedureType(1)
          .terminalIdentifier("CODI8A CODIE 8A (RNAV)")
          .terminalSequenceNumber(20)
          .terminalApproachType("4")
          .transitionIdentifier("ANDOP")
          .icaoCode("YBCS")
          .trackDescriptionCode("TF")
          .termSegWaypointIdentifier("CODIE")
          .waypointCountryCode("AS")
          .terminalWaypointDescriptionCode1("E")
          .terminalWaypointDescriptionCode2("E")
          .cycleDate(202312)
          .waypointGeodeticLatitude("S16324200")
          .waypointDegreesLatitude(-16.545200)
          .waypointGeodeticLongitude("E145355400")
          .waypointDegreesLongitude(145.598133)
          .waypointMagneticVariation(6.482340)
          .build()
  );


}
