package org.mitre.tdp.boogie.dafif;

 import java.util.List;

 import org.mitre.tdp.boogie.dafif.model.DafifAddRunway;
 import org.mitre.tdp.boogie.dafif.model.DafifAirport;
import org.mitre.tdp.boogie.dafif.model.DafifIls;
import org.mitre.tdp.boogie.dafif.model.DafifNavaid;
import org.mitre.tdp.boogie.dafif.model.DafifRunway;
import org.mitre.tdp.boogie.dafif.model.DafifWaypoint;

public class TestObjects {



  public static final DafifNavaid aa = DafifNavaid.builder()
      .navaidIdentifier("AA")
      .navaidKeyCode(0)
      .countryCode("UI")
      .navaidType(5)
      .navaidSlavedVariation(null)
      .cycleDate(201907)
      .degreesLatitude(47.009053)
      .degreesLongitude(-96.815183)
      .build();

  public static final DafifNavaid abr = DafifNavaid.builder()
      .navaidIdentifier("ABR")
      .navaidType(4)
      .navaidKeyCode(0)
      .navaidSlavedVariation("E00700188")
      .cycleDate(202110)
      .degreesLatitude(45.417356)
      .degreesLongitude(-98.368719)
      .build();

  public static final DafifWaypoint fakeAA = DafifWaypoint.builder()
      .waypointIdentifier("N12345")
      .countryCode("UI")
      .waypointType("NR")
      .navaidKeyCode(0)
      .navaidType(5)
      .navaidCountryCode("UI")
      .navaidIdentifier("AA")
      .waypointPointNavaidFlag(true)
      .degreesLatitude(47.009053)
      .degreesLongitude(-96.815183)
      .cycleDate(201907)
      .build();

  public static final DafifAirport fakeAirport = DafifAirport.builder()
      .airportIdentification("FAKE1")
      .icaoCode("IDK1")
      .faaHostCountryIdentifier("AAA")
      .cycleDate(202301)
      .degreesLatitude(12.35)
      .degreesLongitude(23.34)
      .magVarOfRecord("E002065")
      .cycleDate(202110)
      .build();

  public static final DafifAirport fakeAirport2 = DafifAirport.builder()
      .airportIdentification("FAKE2")
      .icaoCode("IDK2")
      .faaHostCountryIdentifier("AAA")
      .cycleDate(202404)
      .degreesLatitude(35.1274)
      .degreesLongitude(-80.9419)
      .magVarOfRecord("W003020")
      .build();

  public static final DafifAirport fakeAirport3 = DafifAirport.builder()
      .airportIdentification("FAKE3")
      .icaoCode("IDK3")
      .faaHostCountryIdentifier("AAA")
      .cycleDate(202404)
      .degreesLatitude(44.9821)
      .degreesLongitude(-93.2731)
      .magVarOfRecord("W001045")
      .build();

  public static final DafifRunway rwy1129 = DafifRunway.builder()
      .lowEndIdentifier("11")
      .highEndIdentifier("29")
      .airportIdentification("FAKE1")
      .highEndMagneticHeading(295.2)
      .lowEndMagneticHeading(115.1)
      .length(9310)
      .width(152)
      .surface("ASP")
      .pavementClassificationNumber("071FAWT")
      .highEndGeodeticLatitude("N12305415")
      .highEndDegreesLatitude(12.508132)
      .highEndGeodeticLongitude("W070002137")
      .highEndDegreesLongitude(-70.018742)
      .highEndElevation("69")
      .highEndSlope("-0.4")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(95)
      .highEndDisplacedThresholdElevation("69")
      .highEndLightingSystem(List.of(12, 6, 49))
      .lowEndGeodeticLatitude("N12311655")
      .lowEndDegreesLatitude(12.514902)
      .lowEndGeodeticLongitude("W070013827")
      .lowEndDegreesLongitude(-70.024611)
      .lowEndElevation("18")
      .lowEndSlope("0.4")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(260)
      .lowEndDisplacedThresholdElevation("18")
      .lowEndLightingSystem(List.of(12, 6, 49))
      .trueHeadingHighEnd(284.2)
      .trueHeadingLowEnd(104.0)
      .highEndLandingDistance(8960)
      .highEndRunwayDistance(9040)
      .highEndTakeOffDistance(9040)
      .highEndAccelerateStopDistance(9040)
      .lowEndLandingDistance(8960)
      .lowEndRunwayDistance(9230)
      .lowEndTakeOffDistance(9230)
      .lowEndAccelerateStopDistance(9230)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifRunway rwy0523 = DafifRunway.builder()
      .lowEndIdentifier("05")
      .highEndIdentifier("23")
      .airportIdentification("FAKE2")
      .highEndMagneticHeading(234.8)
      .lowEndMagneticHeading(54.9)
      .length(7820)
      .width(150)
      .surface("CON")
      .pavementClassificationNumber("055FBCN")
      .highEndGeodeticLatitude("N35124460")
      .highEndDegreesLatitude(35.212667)
      .highEndGeodeticLongitude("W080565200")
      .highEndDegreesLongitude(-80.947222)
      .highEndElevation("745")
      .highEndSlope("0.2")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(120)
      .highEndDisplacedThresholdElevation("746")
      .highEndLightingSystem(List.of(3, 21))
      .lowEndGeodeticLatitude("N35123610")
      .lowEndDegreesLatitude(35.210028)
      .lowEndGeodeticLongitude("W080563520")
      .lowEndDegreesLongitude(-80.942278)
      .lowEndElevation("732")
      .lowEndSlope("-0.2")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(85)
      .lowEndDisplacedThresholdElevation("733")
      .lowEndLightingSystem(List.of(3, 21))
      .trueHeadingHighEnd(235.3)
      .trueHeadingLowEnd(55.2)
      .highEndLandingDistance(7500)
      .highEndRunwayDistance(7820)
      .highEndTakeOffDistance(7820)
      .highEndAccelerateStopDistance(7820)
      .lowEndLandingDistance(7400)
      .lowEndRunwayDistance(7820)
      .lowEndTakeOffDistance(7900)
      .lowEndAccelerateStopDistance(7820)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifRunway rwy0918 = DafifRunway.builder()
      .lowEndIdentifier("09")
      .highEndIdentifier("18")
      .airportIdentification("FAKE3")
      .highEndMagneticHeading(184.0)
      .lowEndMagneticHeading(4.1)
      .length(6100)
      .width(100)
      .surface("ASP")
      .pavementClassificationNumber("040FBDT")
      .highEndGeodeticLatitude("N44585410")
      .highEndDegreesLatitude(44.981694)
      .highEndGeodeticLongitude("W093163800")
      .highEndDegreesLongitude(-93.276667)
      .highEndElevation("840")
      .highEndSlope("0.0")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(60)
      .highEndDisplacedThresholdElevation("840")
      .highEndLightingSystem(List.of(12, 7))
      .lowEndGeodeticLatitude("N44590030")
      .lowEndDegreesLatitude(44.983417)
      .lowEndGeodeticLongitude("W093163450")
      .lowEndDegreesLongitude(-93.279167)
      .lowEndElevation("846")
      .lowEndSlope("0.1")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(35)
      .lowEndDisplacedThresholdElevation("846")
      .lowEndLightingSystem(List.of(12, 7))
      .trueHeadingHighEnd(184.6)
      .trueHeadingLowEnd(4.7)
      .highEndLandingDistance(6000)
      .highEndRunwayDistance(6100)
      .highEndTakeOffDistance(6100)
      .highEndAccelerateStopDistance(6100)
      .lowEndLandingDistance(5950)
      .lowEndRunwayDistance(6100)
      .lowEndTakeOffDistance(6150)
      .lowEndAccelerateStopDistance(6100)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifRunway rwy0220 = DafifRunway.builder()
      .lowEndIdentifier("02")
      .highEndIdentifier("20")
      .airportIdentification("FAKE1")
      .highEndMagneticHeading(204.7)
      .lowEndMagneticHeading(24.9)
      .length(5400)
      .width(100)
      .surface("GRS")
      .pavementClassificationNumber("020FBGR")
      .highEndGeodeticLatitude("N12310010")
      .highEndDegreesLatitude(12.516694)
      .highEndGeodeticLongitude("W070010900")
      .highEndDegreesLongitude(-70.180556)
      .highEndElevation("52")
      .highEndSlope("0.3")
      .highEndTDZE("U")
      .highEndDisplacedThreshold(0)
      .highEndDisplacedThresholdElevation("52")
      .highEndLightingSystem(List.of(0))
      .lowEndGeodeticLatitude("N12310780")
      .lowEndDegreesLatitude(12.518833)
      .lowEndGeodeticLongitude("W070010060")
      .lowEndDegreesLongitude(-70.167222)
      .lowEndElevation("58")
      .lowEndSlope("-0.3")
      .lowEndTDZE("U")
      .lowEndDisplacedThreshold(0)
      .lowEndDisplacedThresholdElevation("58")
      .lowEndLightingSystem(List.of(0))
      .trueHeadingHighEnd(205.3)
      .trueHeadingLowEnd(25.4)
      .highEndLandingDistance(5300)
      .highEndRunwayDistance(5400)
      .highEndTakeOffDistance(5400)
      .highEndAccelerateStopDistance(5400)
      .lowEndLandingDistance(5200)
      .lowEndRunwayDistance(5400)
      .lowEndTakeOffDistance(5450)
      .lowEndAccelerateStopDistance(5400)
      .cycleDate(202404)
      .coordinatePrecision(1)
      .build();

  public static final DafifAddRunway addRunway = DafifAddRunway.builder()
      .airportIdentification("FAKE1")
      .highEndRunwayIdentifier("29")
      .lowEndRunwayIdentifier("11")
      .icaoCode("IDK1")
      .highEndDisplacedThresholdGeodeticLatitude("N12295464")
      .highEndDisplacedThresholdDegreesLatitude(12.498511)
      .highEndDisplacedThresholdGeodeticLongitude("W070001147")
      .highEndDisplacedThresholdDegreesLongitude(-70.003186)
      .highEndOverrunDistance(186)
      .highEndOverrunSurface("ASP")
      .highEndOverrunGeodeticLatitude("N12301657")
      .highEndOverrunDegreesLatitude(12.504604)
      .highEndOverrunGeodeticLongitude("W070014349")
      .highEndOverrunDegreesLongitude(-70.028749)
      .lowEndDisplacedThresholdGeodeticLatitude("N12301550")
      .lowEndDisplacedThresholdDegreesLatitude(12.504306)
      .lowEndDisplacedThresholdGeodeticLongitude("W070013897")
      .lowEndDisplacedThresholdDegreesLongitude(-70.027492)
      .lowEndOverrunSurface("U")
      .cycleDate(202403)
      .build();

  public static final DafifAddRunway addRunway0523 = DafifAddRunway.builder()
      .airportIdentification("FAKE2")
      .highEndRunwayIdentifier("23")
      .lowEndRunwayIdentifier("05")
      .icaoCode("IDK2")
      .highEndDisplacedThresholdGeodeticLatitude("N35124380")
      .highEndDisplacedThresholdDegreesLatitude(35.212167)
      .highEndDisplacedThresholdGeodeticLongitude("W080565470")
      .highEndDisplacedThresholdDegreesLongitude(-80.946389)
      .highEndOverrunDistance(220)
      .highEndOverrunSurface("CON")
      .highEndOverrunGeodeticLatitude("N35124320")
      .highEndOverrunDegreesLatitude(35.211833)
      .highEndOverrunGeodeticLongitude("W080565750")
      .highEndOverrunDegreesLongitude(-80.945556)
      .lowEndDisplacedThresholdGeodeticLatitude("N35123670")
      .lowEndDisplacedThresholdDegreesLatitude(35.210417)
      .lowEndDisplacedThresholdGeodeticLongitude("W080563240")
      .lowEndDisplacedThresholdDegreesLongitude(-80.943000)
      .lowEndOverrunDistance(180)
      .lowEndOverrunSurface("ASP")
      .lowEndOverrunGeodeticLatitude("N35123620")
      .lowEndOverrunDegreesLatitude(35.210111)
      .lowEndOverrunGeodeticLongitude("W080562980")
      .lowEndOverrunDegreesLongitude(-80.942222)
      .cycleDate(202404)
      .build();

  public static final DafifAddRunway addRunway0918 = DafifAddRunway.builder()
      .airportIdentification("FAKE3")
      .highEndRunwayIdentifier("18")
      .lowEndRunwayIdentifier("09")
      .icaoCode("IDK3")
      .highEndDisplacedThresholdGeodeticLatitude("N44585360")
      .highEndDisplacedThresholdDegreesLatitude(44.981333)
      .highEndDisplacedThresholdGeodeticLongitude("W093163860")
      .highEndDisplacedThresholdDegreesLongitude(-93.277000)
      .highEndOverrunDistance(120)
      .highEndOverrunSurface("ASP")
      .highEndOverrunGeodeticLatitude("N44585320")
      .highEndOverrunDegreesLatitude(44.981111)
      .highEndOverrunGeodeticLongitude("W093163950")
      .highEndOverrunDegreesLongitude(-93.277500)
      .lowEndDisplacedThresholdGeodeticLatitude("N44590000")
      .lowEndDisplacedThresholdDegreesLatitude(44.983333)
      .lowEndDisplacedThresholdGeodeticLongitude("W093163420")
      .lowEndDisplacedThresholdDegreesLongitude(-93.279000)
      .lowEndOverrunDistance(90)
      .lowEndOverrunSurface("GRS")
      .lowEndOverrunGeodeticLatitude("N44590040")
      .lowEndOverrunDegreesLatitude(44.983556)
      .lowEndOverrunGeodeticLongitude("W093163380")
      .lowEndOverrunDegreesLongitude(-93.279278)
      .cycleDate(202404)
      .build();

  public static final DafifNavaid fakeVOR = DafifNavaid.builder()
      .navaidIdentifier("FVR")
      .countryCode("UI")
      .navaidKeyCode(0)
      .navaidType(4)
      .navaidSlavedVariation("W00200310")
      .cycleDate(202404)
      .degreesLatitude(35.1203)
      .degreesLongitude(-80.9522)
      .build();

  public static final DafifWaypoint bober = DafifWaypoint.builder()
      .waypointIdentifier("BOBER")
      .countryCode("UI")
      .waypointType("NR")
      .waypointPointNavaidFlag(false)
      .degreesLatitude(47.009053)
      .degreesLongitude(-96.815183)
      .cycleDate(201907)
      .build();

  public static final DafifWaypoint fakeWaypointVorCollocated = DafifWaypoint.builder()
      .waypointIdentifier("FVR")
      .countryCode("UI")
      .waypointType("NR")
      .waypointPointNavaidFlag(false)
      .degreesLatitude(35.1203)
      .degreesLongitude(-80.9522)
      .cycleDate(202404)
      .build();

  public static final DafifWaypoint fakeFix = DafifWaypoint.builder()
      .waypointIdentifier("FIX01")
      .countryCode("UI")
      .waypointType("EN")
      .waypointPointNavaidFlag(false)
      .degreesLatitude(35.1302)
      .degreesLongitude(-80.9306)
      .cycleDate(202404)
      .build();

  public static final  DafifIls fakeIls = DafifIls.builder()
      .runwayIdentifier("11")
      .airportIdentification("FAKE1")
      .ilsNavaidIdentifier("I234")
      .countryCode("AAA")
      .cycleDate(202110)
      .degreesLatitude(12.32)
      .degreesLongitude(23.32)
      .build();

  public static final DafifIls fakeIls05 = DafifIls.builder()
      .runwayIdentifier("05")
      .airportIdentification("FAKE2")
      .ilsNavaidIdentifier("IF05")
      .countryCode("AAA")
      .cycleDate(202404)
      .degreesLatitude(35.2112)
      .degreesLongitude(-80.9441)
      .build();

  public static final DafifIls fakeIls09 = DafifIls.builder()
      .runwayIdentifier("09")
      .airportIdentification("FAKE3")
      .ilsNavaidIdentifier("IF09")
      .countryCode("AAA")
      .cycleDate(202404)
      .degreesLatitude(44.9831)
      .degreesLongitude(-93.2782)
      .build();
}
