deployment-namespace: &deployment-namespace auspicious-abyss

codev-env: &codev-env
  CODEV_USER: ((codev-write.write_user))
  CODEV_PASSWORD: ((codev-write.write_user_token))

github-boogie: &github-boogie
  uri: git@github.com:mitre-tdp/boogie.git
  private_key: ((boogie-deploy-key.ssh-privatekey))
  branch: main

jobs:
  - name: unit-test
    plan:
      - in_parallel:
        - get: concourse-tasks
        - get: application-code
          trigger: true
      - &unit-test-task
        task: test
        file: concourse-tasks/tasks/gradle-task.yaml
        input_mapping: { repo: application-code }
        vars:
          task: testUnit
        params:
          <<: *codev-env
    on_failure: &notify_failure
      put: notify
      params: { alert_type: broke }

  - name: integration-test
    plan:
      - in_parallel:
        - get: concourse-tasks
        - get: application-code
          trigger: true
      - task: test
        file: concourse-tasks/tasks/gradle-task.yaml
        input_mapping: { repo: application-code }
        vars:
          task: testIntegration
        params:
          <<: *codev-env
    on_failure: *notify_failure

  - name: docker-build
    plan:
      - in_parallel:
        - get: concourse-tasks
        - get: application-code
          trigger: true
      - task: build-image
        privileged: true
        file: concourse-tasks/tasks/build-image.yaml
        input_mapping: { dockerfile: application-code }
        params:
          LABEL_org.opencontainers.image.source: "https://github.com/mitre-tdp/boogie"
          LABEL_org.opencontainers.image.description: "TDP independent project for Procedure/Airway/Fix/Airport - related infrastructure parsing and algorithms."
          BUILDKIT_SECRETTEXT_gradle.properties: ((codev-write.gradlePropertiesFile))
      - put: dev-image
        params:
          image: image/image.tar
        get_params: { skip_download: true }
    on_failure: *notify_failure

  - name: helm-validate
    plan:
      - in_parallel:
          - get: concourse-tasks
          - get: application-code
            trigger: true
      - &helm-validate-task
        task: helm-validate
        file: concourse-tasks/tasks/helm-validate.yaml
        input_mapping: { repo: application-code }
    on_failure: *notify_failure

  - name: create-release-candidate
    plan:
      - in_parallel:
          - get: concourse-tasks
          - get: version
            params: { bump: patch }
          - get: application-code
            trigger: true
            passed: [ docker-build, unit-test, integration-test, helm-validate ]
          - get: dev-image
            trigger: true
            params: { format: oci }
            passed: [ docker-build ]
      - task: generate-rc-version
        file: concourse-tasks/tasks/rc-version.yaml
        input_mapping: { repo: application-code }
      - put: candidate-image
        params:
          additional_tags: version/version
          image: dev-image/image.tar
        get_params: { skip_download: true }
      - put: candidate-chart
        params:
          repository: application-code/helm
          version_file: version/version
    on_failure: *notify_failure

  - name: deploy-dev
    plan:
      - in_parallel:
          - get: candidate-chart
            trigger: true
            passed: [ create-release-candidate ]
          - get: dev-deploy-folder
            trigger: true
      - put: helm-dev
        params:
          chart: apps/boogie
          release: boogie
          values: [
            dev-deploy-folder/deploy/common.values.yaml,
            dev-deploy-folder/deploy/dev.values.yaml
          ]
          version: candidate-chart/version
          show_diff: true
        on_failure: *notify_failure
      - put: kubectl-dev
        params: { kubectl: "rollout restart statefulset boogie" }
        on_failure: *notify_failure

  - name: release-gate
    plan:
      - in_parallel:
          - get: concourse-tasks
          - get: dev-pods
            trigger: true
          - get: dev-api-spec
          - get: candidate-image
            passed: [ create-release-candidate ]
          - get: candidate-chart
            passed: [ create-release-candidate ]
      - task: check-pod-status
        file: concourse-tasks/tasks/pod-status.yaml
        input_mapping: { pods: dev-pods, version: candidate-chart }
        params:
          containerSelector: "boogie"

  - name: create-release
    plan:
      - in_parallel:
          - get: concourse-tasks
          - get: version
            params: { bump: patch }
          - get: candidate-image
            params: { format: oci }
            passed: [ release-gate ]
          - get: candidate-chart
            passed: [ release-gate ]
      - put: stable-image
        params:
          additional_tags: version/version
          image: candidate-image/image.tar
        get_params: {skip_download: true}
      - task: repack-chart
        file: concourse-tasks/tasks/package-helm.yaml
        input_mapping: { repo: candidate-chart }
        output_mapping: { packaged-chart: repackaged-chart }
      - put: stable-chart
        params:
          packaged_chart: repackaged-chart
      - put: version
        params: { bump: patch }
    on_failure: *notify_failure

  - name: deploy-prod
    plan:
      - in_parallel:
          - get: stable-chart
            trigger: true
            passed: [ create-release ]
          - get: prod-deploy-folder
            trigger: true
      - put: helm-prod
        params:
          chart: apps/boogie
          release: boogie
          values: [
            prod-deploy-folder/deploy/common.values.yaml,
            prod-deploy-folder/deploy/prod.values.yaml
          ]
          version: stable-chart/version
          show_diff: true
        on_failure: *notify_failure
      - put: kubectl-prod
        params: { kubectl: "rollout restart statefulset boogie" }
        on_failure: *notify_failure

  - name: publish-api
    plan:
      - in_parallel:
          - get: concourse-tasks
          - get: prod-pods
          - get: prod-api-spec
            trigger: true
          - get: stable-chart
            passed: [ deploy-prod ]
      - task: check-pod-status
        file: concourse-tasks/tasks/pod-status.yaml
        input_mapping: { pods: prod-pods, version: stable-chart }
        params:
          containerSelector: "boogie"
      - task: build-api
        file: concourse-tasks/tasks/openapi-codegen.yaml
        input_mapping: { input-spec: prod-api-spec }
        params:
          ARTIFACT_ID: boogie-java-client
      - task: publish-api
        file: concourse-tasks/tasks/gradle-task.yaml
        input_mapping: { repo: generated-client }
        vars:
          task: publish -PtoCodev
        params:
          <<: *codev-env

  - name: reconfigure-self
    plan:
      - get: application-code
        trigger: true
      - set_pipeline: boogie
        file: application-code/.concourse/concourse.yaml
    on_failure: *notify_failure

  - name: test-prs
    plan:
      - in_parallel:
          - get: application-code
            resource: github-pull-requests
            trigger: true
            version: every
          - get: concourse-tasks
      - put: github-pull-requests
        params: { path: application-code, status: pending, context: test }
      - in_parallel:
        - <<: *unit-test-task
        - <<: *helm-validate-task
        - task: fly-validate
          file: concourse-tasks/tasks/fly-validate.yaml
          input_mapping: { repo: github-pull-requests }
          vars:
            pipeline-file: .concourse/concourse.yaml
    on_success:
      put: github-pull-requests
      params: { path: application-code, status: success, context: test }
    on_failure:
      put: github-pull-requests
      params: { path: application-code, status: failure, context: test }
    on_error: &on-error
      put: github-pull-requests
      params: { path: application-code, status: error, context: test }
    on_abort: *on-error

groups:
  - name: release
    jobs:
      - unit-test
      - integration-test
      - docker-build
      - helm-validate
      - create-release-candidate
      - deploy-dev
      - release-gate
      - create-release
      - deploy-prod
      - publish-api
  - name: reconfigure
    jobs: [reconfigure-self, test-prs]

resources:
  - name: github-pull-requests
    type: dynamic-pull-requests
    icon: source-pull
    source:
      repository: mitre-tdp/boogie

  - name: concourse-tasks
    type: concourse-tasks
    icon: &git-icon github

  - name: application-code
    type: git
    icon: *git-icon
    source:
      <<: *github-boogie

  - name: dev-image
    type: ghcr-image
    icon: &image-icon docker
    source:
      repository: ghcr.io/mitre-tdp/tdp/boogie
      tag: latest

  - name: version
    type: semver
    icon: tag
    source:
      <<: *github-boogie
      file: VERSION

  - name: candidate-image
    type: ghcr-image
    icon: *image-icon
    source:
      repository: ghcr.io/mitre-tdp/tdp/boogie
      pre_releases: true

  - name: candidate-chart
    type: helm-chart
    icon: &helm-icon ship-wheel
    source:
      chart: boogie
      include_pre_releases: true

  - name: dev-deploy-folder
    type: git
    icon: github
    source:
      <<: *github-boogie
      paths: [ deploy/dev.values.yaml, deploy/common.values.yaml ]

  - name: kubectl-dev
    type: k8s-dev
    icon: kubernetes
    source:
      namespace: *deployment-namespace

  - name: helm-dev
    type: helm-dev
    icon: kubernetes
    source:
      namespace: *deployment-namespace

  - name: dev-pods
    type: k8s-dev
    icon: kubernetes
    source:
      namespace: *deployment-namespace
      resource_types: pods
      filter:
        name: "boogie*"

  - name: dev-api-spec
    type: http
    icon: code-json
    source:
      url: https://dev.cre.gov.aws.mitre.org/streaming/boogie/v3/api-docs
      insecure: true

  - name: stable-image
    type: ghcr-image
    icon: *image-icon
    source:
      repository: ghcr.io/mitre-tdp/tdp/boogie
      tag: stable

  - name: stable-chart
    type: helm-chart
    icon: *helm-icon
    source:
      chart: boogie

  - name: prod-deploy-folder
    type: git
    icon: github
    source:
      <<: *github-boogie
      paths: [ deploy/prod.values.yaml, deploy/common.values.yaml ]

  - name: kubectl-prod
    type: k8s-prod
    icon: kubernetes
    source:
      namespace: *deployment-namespace

  - name: helm-prod
    type: helm-prod
    icon: kubernetes
    source:
      namespace: *deployment-namespace

  - name: prod-pods # prods
    type: k8s-prod
    icon: kubernetes
    source:
      resource_types: pods
      filter:
        name: "boogie*"

  - name: prod-api-spec
    type: http
    icon: code-json
    source:
      url: https://prod.cre.gov.aws.mitre.org/streaming/boogie/v3/api-docs
      insecure: true

  - name: notify
    type: slack-alert
    icon: slack
    source:
      channel: "#treebeard-n-pippin"