package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE OFFICIAL NAME FOR AN AIRPORT/HELIPORT DESIGNATED BY THE OPERATING  AGENCY OR IN OFFICIAL PUBLICATIONS OF THE COUNTRY IN WHICH THE AIRPORT/HELIPORT IS LOCATED SHALL  ALWAYS BE USED.
 *
 *  THE FOLLOWING SPECIFIC RULES WILL APPLY IN THE ORDER LISTED.
 *
 *  A. U.S. MILITARY OPERATED AIRPORTS WILL TAKE THE NAME AND SPELLING EXACTLY AS DESIGNATED  BY APPROPRIATE MILITARY AUTHORITY, EX. LUKE AFB.
 *
 *  B. U.S. MILITARY COMMAND PREFERENCE WILL TAKE PRECEDENCE OVER OTHER SOURCES.
 *
 *  C. NAMES WHICH ARE DERIVED FROM THE ENGLISH TEXT OF A NATIONAL AERONAUTICAL SOURCE ARE  TO BE USED VERBATIM.
 *
 *  D. WHEN NAMES ARE DERIVED FROM NATIONAL AERONAUTICAL SOURCE WHICH DOES NOT CONTAIN  ENGLISH TEXT, COORDINATION WITH THE NGA ST. LOUIS/TECHNICAL LIBRARY TRANSLATION SECTION IS
 *  REQUIRED TO ESTABLISH THE SPELLING.
 *
 *  E. CITY NAMES SEPARATED BY A DIAGONAL FROM THE AIRPORT NAME WILL NOT BE USED IN THE FILE,
 * FOR EXAMPLE: PARIS/ORLY WILL BE REPORTED AS ORLY; LAMBERT/ST. LOUIS WILL BE REPORTED AS LAMBERT ST  LOUIS. WHEN THE AIRPORT NAME IS COMPOSED OF TWO OR MORE CITY NAMES THEY WILL BE REPORTED, FOR EXAMPLE: MINNEAPOLIS ST PAUL.
 *
 *  F. WHEN THE NAME IS THE SAME AS A GEOGRAPHIC FEATURE OR GEOGRAPHIC PLACE/NAME, AND NONE  OF THE ABOVE SPECIFIED CONDITIONS EXIST, APPLICATION OF BOARD OF GEOGRAPHIC NAMES (BGN)  SPELLING IS REQUIRED.
 *
 *   1. IF NUMERALS ARE REQUIRED, ARABIC NUMERALS SHALL BE USED. NUMERALS ARE NOT PERMITTED AS THE FIRST CHARACTER OF THE AIRPORT/HELIPORT NAME.
 *
 *   2. COMPASS DIRECTIONS OR GEOGRAPHIC TERMS SHALL NOT BE ABBREVIATED.
 *
 *   3. USE OF THE TERM ""NEW"" OR ""OLD"" SHALL BE AVOIDED WHEN ASSIGNING A NAME TO ANY AIRPORT.
 *
 * EXAMPLE(S):
 * H2
 * LAMBERT ST LOUIS INTL
 * ALLINA HOSPITAL AND CLNC OWATONNA HELI
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF NUMBERS 0-9, LETTERS A-Z, SPACES
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 */
public final class AirportHeliportName extends TrimmableString {

  @Override
  public int maxFieldLength() {
    return 38;
  }

  @Override
  public int fieldCode() {
    return 52;
  }

  @Override
  public String regex() {
    return "([A-Z0-9][A-Z0-9 ]{0,37})";
  }
}
