package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * DESIGNATES WHETHER THE REFERENCED WAYPOINT IDENTIFIED IN THE WAYPOINT IDENTIFIER SHOULD BE CROSSED "AT" (NULL), "AT OR ABOVE" (+), "BETWEEN" (B), OR OTHER SPECIFIC TYPES OF ALTITUDES.
 *
 * + =AT OR ABOVE ALTITUDE SPECIFIED IN ALTITUDE ONE.
 * - =AT OR BELOW ALTITUDE SPECIFIED IN ALTITUDE ONE.
 * NULL=AT ALTITUDE SPECIFIED IN ALTITUDE ONE.
 * B=BETWEEN ALTITUDES SPECIFIED IN ALTITUDE ONE AND ALTITUDE TWO.
 * C=AT OR ABOVE ALTITUDE TWO
 * G=INDICATES 'AT' ALTITUDE IN ALT_ONE AND GLIDE SLOPE ALTITUDE IN ALT_TWO.
 * H=INDICATES 'AT OR ABOVE' ALTITUDE IN ALT_ONE AND GLIDE SLOPE ALTITUDE IN ALT_TWO.
 * I=INDICATES 'AT' ALTITUDE IN ALT_ONE AND GLIDE SLOPE INTERCEPT ALTITUDE IN ALT_TWO.
 * J=INDICATES 'AT OR ABOVE' ALTITUDE IN ALT_ONE AND GLIDE SLOPE INTERCEPT ALTITUDE IN ALT_TWO.
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * +, -, NULL, B, C, G, H, I, J
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * ***CRITICAL CHANGE***   THE ALTITUDE CODES IN ED8.0 ARE NOT THE SAME AS IN ED8.1.    SINCE ED8.0 HAS NO ALTITUDE DESCRIPTOR CODES EQUIVALENT TO 'C', 'G', OR 'I', NO ED8.1 PROCEDURES  CONTAINING THESE CODES WILL BE AVAILABLE IN ED 8.0.
 *
 *  NOTES:
 * 1.  ALT_ONE WILL ALWAYS BE NULL AND ALT_TWO IS REQUIRED FOR 'C'.
 * 2.  BOTH ALT_ONE AND ALT_TWO ARE REQUIRED FOR ‘B’, 'G','H','I'.
 *
 * '+'  (PLUS)-INDICATES 'AT OR ABOVE' ALTITUDE IN ALT_ONE FIELD, ALT_TWO WILL BE NULL.
 *
 * '-'  (MINUS)-INDICATES 'AT OR BELOW' ALTITUDE IN ALT_ONE FIELD, ALT_TWO WILL BE NULL.
 *
 * (NULL)-INDICATES 'AT' ALTITUDE IN ALT_ONE FIELD, ALT_TWO WILL BE NULL.
 *
 * B-INDICATES 'BETWEEN' ALTITUDES.  ALT_ONE WILL INDICATE 'AT OR BELOW' ALTITUDE AND ALT_TWO WILL INDICATE 'AT OR ABOVE' ALTITUDE.
 *
 * C-INDICATES 'AT OR ABOVE' ALTITUDE SPECIFIED IN ALT_TWO.  ALT_ONE WILL BE NULL.  WILL ONLY BE PRESENT IN SID (TYPE 2) PROCEDURES, WHEN SOURCED, AND WHEN A CONDITIONAL ALTITUDE APPLIES TO THE LEG.
 *
 * G-INDICATES 'AT' ALTITUDE IN ALT_ONE AND GLIDE SLOPE ALTITUDE IN ALT_TWO.  WILL ONLY BE USED ON THE FAF WAYPOINT WHEN WPT_DESC_4='F' ON IAP (TYPE 3) WITH ELETRONIC GLIDE SLOPE (TYPE 3 WHERE TRM_IDENT LIKE 'I****').
 *
 * H-INDICATES 'AT OR ABOVE' ALTITUDE IN ALT_ONE AND GLIDE SLOPE ALTITUDE IN ALT_TWO.  WILL ONLY BE USED ON THE FAF WAYPOINT WHEN WPT_DESC_4='F' ON INSTRUMENT APPROACH PROCEDURES WITH ELECTRONIC GLIDE SLOPE (TYPE 3 WHERE TRM_IDENT LIKE 'I****').
 *
 * I-INDICATES 'AT' ALTITUDE IN ALT_ONE AND GLIDE SLOPE INTERCEPT ALTITUDE IN ALT_TWO.  WILL ONLY BE USED ON THE FACF WAYPOINT WHEN WPT_DESC_4='I' ON INSTRUMENT APPROACH PROCEDURES WITH ELECTRONIC GLIDE SLOPE (TYPE 3 WHERE TRM_IDENT LIKE 'I****').
 *
 * J-INDICATES 'AT OR ABOVE' ALTITUDE IN ALT_ONE AND GLIDE SLOPE INTERCEPT ALTITUDE IN ALT_TWO.  WILL ONLY BE USED ON THE FACF WAYPOINT WHEN WPT_DESC_4='I' ON INSTRUMENT APPROACH PROCEDURES WITH ELECTRONIC GLIDE SLOPE (TYPE 3 WHERE TRM_IDENT LIKE 'I****').
 *
 * NOTE:  THERE WILL BE OCCASIONS WHERE THE ALT_DESC IS NULL, ALT_ONE IS NULL, AND ALT_TWO IS NOT NULL.  THIS SITUATION WILL ONLY OCCUR ON INSTRUMENT APPROACH PROCEDURES WITH ELECTRONIC GLIDE SLOPE (TYPE 3 WHERE TRM_IDENT LIKE 'I****') AND WHERE NO GOVERNMENT SOURCED ALTITUDE IS AVAILABLE FOR THE FACF WAYPOINT WHEN WPT_DESC_4='I'.  ALT_TWO INDICATES GLIDE SLOPE INTERCEPT ALTITUDE.
 */
public final class AltitudeDescription extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 21;
  }

  @Override
  public String regex() {
    return "((\\+|\\-|B|C|G|H|I|J)?)";
  }
}