package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * SUPPLEMENTS THE ROUTE 'TYPE' IN THE SEGMENT RECORD.  THE TYPE IN THE SEGMENT RECORD IS THE  PRIMARY AND THE ROUTE QUALIFIER IS THE SECONDARY. THE SECONDARY ROUTE QUALIFIER APPLIES  TO GPS AND RNAV TYPE PROCEDURES.
 *
 * EXAMPLE(S):
 * A
 * F
 * N
 * NULL
 *
 *  PRIMARY APCH_RTE_QUAL1 ENTRY:
 *    A - ADVANCED  (RNAV/RNP, SAAAR/AR NOT REQUIRED)
 *    B - RNAV VISUAL PROCEDURE
 *    D - DME REQUIRED FOR THE PROCEDURE
 *    F - SAAAR/AR PROCEDURE (RNAV/RNP)
 *    J - RNAV, GPS REQUIRED, DME/DME TO RNP X.X NOT AUTHORIZED
 *    L - GBAS PROCEDURE
 *    N - DME NOT REQUIRED FOR THE PROCEDURE
 *    P - GNSS REQUIRED FOR PROCEDURE
 *    R - RNAV, GPS OR DME/DME TO RNP X.X REQUIRED FOR PROCEDURE
 *    T - DME/DME REQUIRED FOR PROCEDURE
 *    U - RNAV, SENSOR NOT SPECIFIED IN SOURCE
 *    V - VOR/DME RNAV
 *    W - RNAV PROCEDURE REQUIRING A FAS DATA BLOCK
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * A,B,D,F,J,L,N,P,R,T,U,V,W
 * OR
 * NULL
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * APCH_RTE_QUAL1 IS USED TO FILTER PROCEDURES THAT EXCEED INDIVIDUAL AIRFRAME/AIRCREW CAPABILITIES.
 */
public final class ApproachRouteQualifier1 extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 447;
  }

  @Override
  public String regex() {
    return "((A|B|D|F|J|L|N|P|R|T|U|V|W)?)";
  }
}