package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * SUPPLEMENTS THE ROUTE 'TYPE' IN THE SEGMENT RECORD.  THE TYPE IN THE SEGMENT RECORD IS THE PRIMARY AND THE ROUTE QUALIFIER IS THE SECONDARY.  THE SECONDARY ROUTE QUALIFIER APPLIES  TO GPS AND RNAV TYPE PROCEDURES.
 *
 * EXAMPLE(S):
 * A
 * L
 * S
 * NULL
 *
 *  SECONDARY APCH_RTE_QUAL2 ENTRY:
 *    A - PRIMARY MISSED APPROACH
 *    B - SECONDARY MISSED APPROACH
 *    C - PROCEDURE WITHOUT STRAIGHT IN MINIMUMS
 *    E - ENGINE OUT MISSED APPROACH
 *    H - HELICOPTER WITH STRIAIGHT IN MINIMUMS
 *     I - HELICOPTER WITH CIRCLE TO LAND MINIMUMS
 *    L - HELICOPTER WITH HELICOPTER LANDING MINIMUMS
 *    S - PROCEDURE WITH STRAIGHT IN MINIMUMS
 *    V - PROCEDURE WITH VMC MINIMUMS
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * A,B,C,E,H,I,L,S,V
 * OR
 * NULL
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * APCH_RTE_QUAL2 IS USED TO FILTER CIRCLING/STRAIGHT-IN/HELICOPTER PROCEDURES.
 */
public final class ApproachRouteQualifier2 extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 269;
  }

  @Override
  public String regex() {
    return "((A|B|C|E|H|I|L|S|V)?)";
  }
}