package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * SEQUENCE NUMBERS ARE DESIGNED TO BE USED IN CONJUNCTION WITH ATS ROUTE IDENTIFIERS TO FORM A UNIQUE METHOD OF IDENTIFYING A PARTICULAR ATS ROUTE SEGMENT WITHIN DAFIF.  THEY DEFINE THE RELATIVE POSITION OF THE SEGMENT IN THE TOTAL ATS ROUTE WHILE GIVING THE SEQUENTIAL ORDER OF THE ATS ROUTE SEGMENTS.
 *
 * IF BIDIRECT=NULL, THEN THE ATS ROUTE IS A ONE WAY ROUTE EITHER EASTBOUND OR WESTBOUND AND THEY WILL ADHERE TO THE FOLLOWING SEQUENCE NUMBER CRITERIA:
 * -EASTBOUND ROUTE (DIRECTION=E) SEQUENCE NUMBERS WILL BE MULTIPLES OF 10 BEGINNING AT 10 (10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110…) AND WILL NEVER EXCEED 5000.
 * -WESTBOUND ROUTE (DIRECTION=W) SEQUENCE NUMBERS WILL BE MULTIPLES OF 10 ENDING AT 9990 (…9880, 9890, 9900, 9910, 9920, 9930, 9940, 9950, 9960, 9970, 9980, 9990) AND WILL NEVER BE LESS THAN 5000.
 *
 * IF THE BIDIRECT=Y, THEN THE ATS ROUTE IS DESIGNED FOR TWO WAY TRAFFIC.  DAFIF WILL GENERATE ONE EASTBOUND ROUTE AND ONE WESTBOUND ROUTE WITH THE SAME POINTS.  THE SAME SEQUENCE NUMBER CRITERIA STATED ABOVE IS APPLIED TO THESE ROUTES.
 *
 * FIELD TYPE: N
 *
 * ALLOWED VALUES:
 * 10-9990 (LEADING ZEROS ARE SUPPRESSED, THE LAST CHARACTER IS ALWAYS A ZERO)
 *
 * SOURCE: SYSTEM GENERATED
 *
 * INTENDED USE:
 * INCREASING SEQUENCE NUMBERS START AT 10 WITH UNITS INCREASING IN UNITS OF 10. DECREASING SEQUENCE NUMBERS START AT 9990 WITH UNITS DECREASING IN UNITS OF 10.
 *
 * NOTE:  THERE IS NO RELATIONSHIP BETWEEN SEQ_NBR AND TRACK DESCRIPTION CODE OR WAYPOINT DESCRIPTION CODES 1-4.
 */
public final class AtsRouteSequenceNumber extends DafifInteger {
  @Override
  public int maxFieldLength() {
    return 4;
  }

  @Override
  public int fieldCode() {
    return 40;
  }

  @Override
  public String regex() {
    return "([1-9][0-9]{0,2}0)";
  }
}