package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * ENABLES THE FUNCTION OF A WAYPOINTS LOCATION TO BE IDENTIFIED.
 *
 *  WAYPOINT DESCRIPTION CODE 1:
 *    E - ESSENTIAL WAYPOINT
 *    R - NONESSENTIAL WAYPOINT
 *    N - NDB, NDB/DME
 *    V - VOR, VOR-DME, VORTAC, TACAN, DME
 *
 * ESSENTIAL:  AN ESSENTIAL WAYPOINT IS DEFINED AS ANY WAYPOINT AT WHICH A CHANGE IN COURSE IS  REQUIRED OR WHERE TWO OR MORE ROUTES INTERSECT.  NOTE: THE TERM "INTERSECT" INCLUDES THOSE
 *  INSTANCES WHEN THE ROUTE DESIGNATOR (INCLUDES PREFIX BUT EXCLUDES SUFFIX) CHANGES WITH NO  CHANGE IN COURSE (EX. UA470, UA469 OR UA470, A470).
 *
 *  NON-ESSENTIAL:  NONESSENTIAL WAYPOINTS INCLUDE ALL OTHER WAYPOINTS OF A ROUTE NOT  INCLUDED UNDER ESSENTIAL.
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * E, R, V, N
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * WHEN WPT1_DESC_1 (AND/OR WPT2_DESC_1) IS SET TO NAVAID (V, N), THE PLANNING SYSTEM MUST USE  THE REFERENCED WAYPOINT TO LOCATE THE ASSOCIATED NAVAID WHICH IS STORED IN THE DAFIF NAV  TABLE AND REPLACE THE REFERENCED WAYPOINT WITH THE NAVAID INFORMATION.
 */
public final class AtsWaypointDescriptionCode1 extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 337;
  }

  @Override
  public String regex() {
    return "(E|R|V|N)";
  }
}