package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * "COUNTRY CODE" IS A TWO LETTER IDENTIFICATION.THE CURRENT DAFIF OUTPUT REFLECTS COUNTRY CODE VALUES AS REFLECTED IN FIPS PUB 10-4.
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF LETTERS AA-ZZORNULL
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * TRM_SEG-NAV1_CTRY:  POPULATED WHEN PATH TERMINATOR OR PARTICULAR PHASE OF THE PROCEDURE REQUIRES IT.
 * SEE REQUIRED FIELD MATRIX IN APPENDIX D.NAV2_CTRY:  NOT MAINTAINED IN DAFIF 8.1.THE ATS_CTRY, NAV, AND
 * WPT TABLES UTILIZE THE CTRY FIELD AS A KEY FIELD.  THE ARF_PAR, MTR_PR, AND VFR_RTE TABLES DO NOT.
 */
public final class CountryCode extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 2;
  }

  @Override
  public int fieldCode() {
    return 95;
  }

  @Override
  public String regex() {
    return "(([A-Z]{2})?)";
  }
}