package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE LONGITUDE OF A POINT EXPRESSED IN A DECIMAL DEGREE COORDINATE (THE INTERSECTION OF LINES OF REFERENCE IN CONJUNCTION WITH LATITUDE USED TO DETERMINE POSITION OR LOCATION).
 *
 * IN THE CASE OF DME_WGS_DLONG, THE POINT IS DERIVED BY SURVEY.
 *
 * FIELD TYPE: N
 *
 * ALLOWED VALUES:
 * 0.000000 THROUGH 180.000000
 * OR
 * -0.000001 THROUGH -179.999999
 * (LEADING ZEROS SUPPRESSED UNLESS VALUE IS LESS THAN 1.000000 OR GREATER THAN -1.000000, THERE WILL ALWAYS BE 6 DIGITS AFTER THE DECIMAL)
 * OR
 * NULL
 *
 * SOURCE: SYSTEM GENERATED
 *
 * INTENDED USE:
 * CALCULATED BY CONVERTING SPECIFIC COORDINATES FROM DMS FORMAT TO DDS.  IF THERE IS NO DMS  VALUE (NULL FIELD), THERE WILL BE NO DDS VALUE POPULATED.
 */
public final class DmeDegreesLongitude extends DafifDouble {
  @Override
  public int maxFieldLength() {
    return 11;
  }

  @Override
  public int fieldCode() {
    return 362;
  }

  @Override
  public String regex() {
    return "(((\\-)?([0-9]|[1-9][0-9]|1[0-7][0-9])\\.[0-9]{6}|( ){7}-180|( ){8}180)?)";
  }
}