package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * A GEOGRAPHICAL POSITION DETERMINED BY REFERENCE TO A NAVIGATIONAL AID.
 *
 * DME FIX - A GEOGRAPHICAL POSITION DETERMINED BY REFERENCE TO A NAVIGATIONAL AID WHICH  PROVIDES AZIMUTH AND DISTANCE INFORMATION.  IT IS DEFINED BY A SPECIFIC SLANT RANGE DISTANCE
 * IN NAUTICAL MILES AND TENTHS OF NAUTICAL MILES, AND BEARING IN DEGREES AND TENTHS OF  DEGREES MAGNETIC FROM THAT NAVIGATIONAL AID.
 *
 * NON-DME FIX - A GEOGRAPHICAL POSITION DETERMINED BY REFERENCE TO A NAVIGATIONAL AID  WHICH PROVIDES BEARING AND DISTANCE INFORMATION.  IT IS DEFINED BY A SPECIFIC DISTANCE IN NAUTICAL MILES AND TENTHS OF NAUTICAL MILES, AND BEARING IN DEGREES AND TENTHS OF DEGREES  MAGNETIC FROM THAT NAVIGATIONAL AID.
 *
 * 0.0 IS REQUIREDFOR CERTAIN TRACK CODES BUT IS NOT A BEARING.
 *
 * EXAMPLE(S):
 * 242.0
 * 0.0
 * NULL
 *
 * FIELD TYPE: N
 *
 * ALLOWED VALUES:
 * (RADIAL, AZIMUTH, COURSE OR BEARING)
 * 0.0 – 360.0 (LEADING ZEROS SUPPRESSED UNLESS VALUE IS LESS THAN 1.0, THERE WILL ALWAYS BE A DIGIT AFTER THE DECIMAL)
 * OR
 * NULL
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 *
 * INTENDED USE:
 * NAV1_BEAR:  POPULATED WHEN PATH TERMINATOR OR PARTICULAR PHASE OF THE PROCEDURE REQUIRES IT.  SEE REQUIRED FIELD MATRIX IN APPENDIX D.
 * NAV2_BEAR:  NOT MAINTAINED IN DAFIF 8.1.
 *
 * THIS VALUE WILL BE NGA ORIGINATED WHEN NECESSARY TO SUPPORT PROCEDURE CODING AND TO SATISFY PROCEDURE DESIGN INTENT.
 */
public final class Fix12Bearing extends DafifDouble {
  @Override
  public int maxFieldLength() {
    return 5;
  }

  @Override
  public int fieldCode() {
    return 113;
  }

  @Override
  public String regex() {
    return "((0\\.[0-9]|360.0|([1-9][0-9]{0,1}|[1-2][0-9]{1,2}|3[0-5][0-9])\\.[0-9])?)";
  }
}