package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * A GEOGRAPHICAL POSITION DETERMINED BY REFERENCE TO A NAVIGATIONAL AID.
 *
 * DME FIX - A GEOGRAPHICAL POSITION DETERMINED BY REFERENCE TO A NAVIGATIONAL AID WHICH  PROVIDES AZIMUTH AND DISTANCE INFORMATION.  IT IS DEFINED BY A SPECIFIC SLANT RANGE DISTANCE
 *  IN NAUTICAL MILES AND TENTHS OF NAUTICAL MILES, AND BEARING IN DEGREES AND TENTHS OF  DEGREES MAGNETIC FROM THAT NAVIGATIONAL AID.
 *
 *  NON-DME FIX - A GEOGRAPHICAL POSITION DETERMINED BY REFERENCE TO A NAVIGATIONAL AID  WHICH PROVIDES BEARING AND DISTANCE INFORMATION.  IT IS DEFINED BY A SPECIFIC DISTANCE IN  NAUTICAL MILES AND TENTHS OF NAUTICAL MILES, AND BEARING IN DEGREES AND TENTHS OF DEGREES MAGNETIC FROM THAT NAVIGATIONAL AID.
 *
 * EXAMPLE(S):
 * 48.0
 * 199.9
 * 0.0
 *
 * FIELD TYPE: N
 *
 * ALLOWED VALUES:
 * 0.0 - 999.9 (LEADING ZEROS ARE SUPPRESSED EXCEPT WHEN LESS THAN 1.0)
 * OR
 * NULL
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 *
 * INTENDED USE:
 * NAV1_DIST:  POPULATED WHEN PATH TERMINATOR OR PARTICULAR PHASE OF THE PROCEDURE REQUIRES IT.  SEE REQUIRED FIELD MATRIX IN APPENDIX D.
 * NAV2_DIST:  NO LONGER MAINTAINED IN DAFIF.
 *
 * THIS VALUE WILL BE NGA ORIGINATED WHEN NECESSARY TO SUPPORT PROCEDURE CODING AND TO SATISFY PROCEDURE DESIGN INTENT.
 */
public final class Fix12Distance extends DafifDouble {
  @Override
  public int maxFieldLength() {
    return 5;
  }

  @Override
  public int fieldCode() {
    return 114;
  }

  @Override
  public String regex() {
    return "((0\\.[0-9]|([1-9][0-9]{0,2})\\.[0-9])?)";
  }
}