package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE HOST COUNTRY AGENCY THAT HAS AUTHORITY FOR THE SPECIFIED TERMINAL PROCEDURE.
 *
 * EXAMPLES:
 * CIV
 * MIL
 * NULL
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF LETTERS A-Z AND SPACES
 * OR
 * NULL
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * WHEN DETERMINING THE PEDIGREE OF A TERMINAL PROCEDURE IN DAFIF, USE THE ARPT_IDENT TO IDENTIFY THE COUNTRY THE PROCEDURE CAME FROM, THE OPR FIELD TO IDENTIFY WHO IS RESPONSIBLE FOR CODING THE PROCEDURE, AND THE HOST_CTRY_AUTH TO DETERMINE IF THE AIP IS CIVIL OR MILITARY.
 *
 * EXAMPLE 1:
 * ARPT_IDENT = NO91674: THE PROCEDURE WAS DEVELOPED IN NORWAY
 * OPR = AIDU: THE PROCEDURE WAS CODED BY THE UNITED KINGDOM (AIDU)
 * HOST_CTRY_AUTH = CIV: THE PROCEDURE CAME OUT OF THE CIVIL AIP
 *
 * EXAMPLE 2:
 * ARPT_IDENT = CA25699: THE PROCEDURE WAS DEVELOPED IN CANADA
 * OPR = DNGA: THE PROCEDURE WAS CODED BY NGA
 * HOST_CTRY_AUTH = MIL: THE PROCEDURE CAME OUT OF THE MILITARY AIP
 *
 * EXAMPLE 3:
 * ARPT_IDENT = FR00699: THE PROCEDURE WAS DEVELOPED IN FRANCE
 * OPR = FR: THE PROCEDURE WAS CODED BY THE FRENCH AVIATION AUTHORITY
 * HOST_CTRY_AUTH = CIV: THE PROCEDURE CAME OUT OF THE CIVIL AIP
 */
public final class HostCountryAuthority extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 10;
  }

  @Override
  public int fieldCode() {
    return 144;
  }

  @Override
  public String regex() {
    return "((CIV|MIL)?)";
  }
}