package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * INTERNATIONAL CIVIL AVIATION ORGANIZATION (ICAO) LOCATION IDENTIFIERS.
 *
 * THE MILITARY ICAO IDENTIFIER WILL TAKE PRECEDENCE AT MILITARY OR JOINT USE AIRPORTS (ARPT.TYPE = B OR C).
 *
 * WAYPOINT ICAO CODE BASED ON THE CONTROLLING ACC ICAO CODE
 *
 * EXAMPLE(S):
 * YBBB
 * PP
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF LETTERS A-Z
 *  (CAN BE EITHER A TWO OR FOUR CHARACTER CODE)
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * ATS ROUTE:  THE WAYPOINT ICAO IS GENERATED FROM THE WAYPOINT RECORD ON OUTPUT.
 *
 * WHEN THE AIRPORT DOES NOT HAVE A FOUR LETTER ICAO CODE FROM ICAO DOCUMENT 7910, REFERENCE THE FAA_HOST_ID COLUMN IN THE ARPT TABLE FOR EITHER THE HOST ASSIGNED OR NGA DERIVED IDENT.
 */
public final class IcaoCode extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 4;
  }

  @Override
  public int fieldCode() {
    return 146;
  }

  @Override
  public String regex() {
    return "([A-Z]{2}|[A-Z]{4})";
  }
}