package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE ELEVATION IN FEET FROM MEAN SEA LEVEL (MSL) AS MEASURED AT THE BASE OF THE ANTENNA.
 * A VALUE OF 0 INDICATES AN ELEVATION OF MSL, AND A NEGATIVE VALUE INDICATES AN ELEVATION BELOW MSL.
 *
 *
 * EXAMPLE(S):
 * 00062
 * -0035
 * -1200
 * 00000
 * 29011
 * U
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * -1299 - 29029  (PADDED WITH LEADING ZEROS)
 * OR
 * U (UNKNOWN)
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 *
 * INTENDED USE:
 * IF THE AERO NAVIGATION SOURCE PROVIDER (ANSP) DOES NOT PROVIDE AN ILS COMPONENT ELEVATION, A VALUE OF ""U""
 * (UNKNOWN) WILL BE POPULATED FOR ILS COMPONENT TYPES (B,I,L,M,O,P,S,V,Z). FOR ILS COMPONENT TYPES (D AND G),
 * IF THE ANSP DOES NOT PROVIDE AN ELEVATION AND THE COMPONENT IS ON THE AIRFIELD, AIRFIELD ELEVATION WILL BE POPULATED.
 * IF THE COMPONENT IS NOT ON THE AIRFIELD, AN ELEVATION WILL BE CALCULATED.
 * IF THE ANSP DOES NOT PROVIDE A NAVAID ELEVATION FOR COMPONENT TYPE 5 (NDB), A VALUE OF “U” (UNKNOWN) WILL BE POPULATED.
 * FOR NAVAID COMPONENT TYPES (1,2,3,4,7,9) IF THE ANSP DOES NOT PROVIDE AN ELEVATION AND THE COMPONENT IS ON THE AIRFIELD,
 * AIRFIELD ELEVATION WILL BE POPULATED. IF THE COMPONENT IS NOT ON THE AIRFIELD, AN ELEVATION WILL BE CALCULATED.
 *
 * THIS VALUE MAY BE DERIVED IN THE ABSENSE OF HOST PROVIDED VALUES USING IMAGERY OR MENSURATION TO PROVIDE
 * PRECISE MEASUREMENT FOR THIS FIELD IN ACCORDANCE WITH DO-200B AND DO-201.
 */
public class IlsNavaidElevation extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 5;
  }

  @Override
  public int fieldCode() {
    return 106;
  }

  @Override
  public String regex() {
    return "((\\-)?[0-9]{1,5}|U)";
  }
}
