package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * "SLAVE" OR "ASSIGNED" VARIATION IS A FIXED VALUE OF MAGNETIC VARIATION APPLIED TO TRUE
 * DIRECTION TO OBTAIN THE MAGNETIC VALUES FOR RADIALS, COURSES, AND HEADINGS.  THIS IS
 * ESTABLISHED BY A MECHANICAL ADJUSTMENT TO THE NAVAID EQUIPMENT, AND IS ONLY CHANGED
 * WHEN SLAVED NORTH VARIES FROM MAGNETIC NORTH BY AN AMOUNT ESTABLISHED BY THE  CONTROLLING AGENCY.
 * CHARACTERS ONE THROUGH FOUR ARE THE VARIATION IN WHOLE DEGREES. THE FIFTH CHARACTER IS A SPACE
 * (WHOLE DEGREES ONLY; NO TENTH INDICATED). THE LAST FOUR CHARACTERS INDICATE THE MONTH AND
 * YEAR OF VARIATION. IF NO SLAVE VAR IS PROVIDED BY HOST, 0165 (JANUARY 1965) WILL BE INSERTED.
 *
 * EXAMPLES:
 * W010 0413 (W010 APR 2013)
 * E013 1212 (E013 DEC 2012)
 * E002 0165 (E002 JAN 1965)
 * IF HOST DOES NOT SUPPLY SLAVE VARIATION, DAFIF WILL OUTPUT DYNAMIC MAGVAR THAT IS UPDATED YEARLY.
 * A LIST OF ILS COMPONENTS THAT CONTAIN DYNAMIC MAGVAR CAN BE OBTAINED FROM NGA BY REQUEST.
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 *  E000 0100-E180 1299
 *  OR
 *  W001 0100-W179 1299
 *  OR
 *  NULL
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 *
 * INTENDED USE:
 * WHEN COMPONENT TYPE = Z, THIS FIELD WILL NOT BE NULL.
 */
public final class IlsSlaveVariation extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 9;
  }

  @Override
  public int fieldCode() {
    return 273;
  }

  @Override
  public String regex() {
    return "(((E0[0-9]{2}|E1[0-7][0-9]|E180|W0[0-9][1-9]|W0[1-9][0-9]|W1[0-7][0-9])[ ](0[1-9][0-9]{2}|1[0-2][0-9]{2}))?)";
  }
}