package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * TOTAL DISTANCE IN FEET OF RUNWAY (PHYSICAL END TO PHYSICAL END) INCLUDING DISPLACED  THRESHOLDS, TURNING  CIRCLES AND ENDS OF ABUTTING RUNWAYS, BUT NOT INCLUDING OVERRUNS OR BLAST PADS.
 *
 * NOTE:  WHEN THE PRIMARY RUNWAY IS UNDER CONSTRUCTION AND A PORTION OF IT IS USABLE TO THE  EXTENT THAT IT RETAINS THE GREATEST LENGTH OF OPERATIONAL CAPABILITY, THE USABLE LENGTH  AND OTHER PERTINENT DATA WILL BE ENTERED.
 *
 * EXAMPLE(S):
 * 00575
 * 11500
 *
 * FIELD TYPE: N
 *
 * ALLOWED VALUES:
 * 00001-40000 (PADDED WITH LEADING ZEROS)
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 *
 * INTENDED USE:
 * THE RUNWAY AVAILABLE FOR PLANNING AND CIVIL AVIATION OPERATIONS MAY BE DIFFERENT THAN THE PHYSICAL RUNWAY LENGTH.
 *
 * THIS VALUE MAY BE DERIVED IN THE ABSENSE OF HOST PROVIDED VALUES USING IMAGERY OR MENSURATION TO PROVIDE PRECISE MEASUREMENT FOR THIS FIELD IN ACCORDANCE WITH DO-200B AND DO-201.
 */
public final class Length extends DafifInteger {
  @Override
  public int maxFieldLength() {
    return 5;
  }

  @Override
  public int fieldCode() {
    return 162;
  }

  @Override
  public String regex() {
    return "(0([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]|[0-9][1-9][0-9]{2}|[1-9][0-9]{3})|[1-3][0-9]{4}|40000)";
  }
}