package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * IDENTIFIES THE OFFICIAL PROCEDURE LEVEL OF SERVICE BASED ON PUBLISHED PROCEDURE OPERATING MINIMUMS FOR APPROACH PROCEDURES AUTHORIZED FOR SATELLITE BASED AUGMENTATION SYSTEMS (SBAS).
 *
 * EXAMPLE(S):
 * LP
 * LPV
 * LPV200
 * RNP 0.30
 * RNP 0.11
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * COMBINATION OF LETTERS A-Z
 * NUMBERS 0-9
 * SPACES AND SPECIAL CHARACTERS
 * OR
 * NULL
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * LOS_NAME1:  LPV, LP, OR LPV200 - REQUIRES FAS DATA BLOCK - PAPP RECORD SHOULD BE POPULATED.
 *
 * LOS1:  UTILIZED FOR PRECISION RNAV
 *
 * THIS FIELD IS ALSO USED TO IDENTIFY RNP MINIMA ON RNP AR PROCEDURES. THE FORMAT WILL BE THE RNP LEVEL CONTAINED IN THE LINE OF MINIMA FROM THE LEAST RESTRICTIVE TO MOST RESTRICTIVE. IF FOUR OR MORE LINES OF MINIMA ARE SOURCED, THE LEAST RESTRICTIVE WILL GO IN THE TERMINAL SEGMENTS AND THE REST WILL FOLLOW IN LOS_NAME1 THRU 3. FOR EXAMPLE, 0.30 WILL GO IN TERM_SEG, AND  0.22, 0.15, 0.11 WILL GO IN LOS_NAME1 THRU 3. IF LESS THAN FOUR LINES OF MINIMA ARE SUPPLIED, THE LEAST RESTRICTIVE WILL BE POPULATED IN THE TERMINAL SEGMENTS, AND ALL LINES OF MINIMA WILL BE POPULATED IN LOS_NAME1 THRU LOS_NAME3.
 */
public final class LevelOfService1 extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 10;
  }

  @Override
  public int fieldCode() {
    return 433;
  }

  @Override
  public String regex() {
    return "((LP|LPV|LPV200|RNP [0-1]\\.[0-9]{2})?)";
  }
}