package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE FIRST CHARACTER DESIGNATES THE POSITION OF THE LOCALIZER ANTENNA OR GLIDESLOPE (GS)  FACILITIES IN RELATION TO THE RUNWAY.
 *
 *  (-) - PRIOR TO THE APPROACH END.
 *  (SPACE) - DISPLACED TO ONE SIDE OF THE RUNWAY.
 *  (+) - BEYOND THE STOP END (VALUE FROM STOP END OF RUNWAY).
 *
 * NOTE:  ""DISPLACED TO ONE SIDE"" IS USED ONLY WHEN THE LOCALIZER/GS ANTENNA IS OFFSET  PERPENDICULAR TO THE RUNWAY (NOT EXTENDED CENTERLINE).
 *
 * NOTE:  THE REMAINING CHARACTERS DEFINE THE LOCATION (IN FEET) FROM THE LOCALIZER ANTENNA  OR GS FACILITY.  THE LOCALIZER/GS ARE MEASURED FROM THE END OF THE RUNWAY TO THE ANTENNA WHEN THE FIRST CHARACTER IS A + OR -.  THE LOCALIZER/GS ARE MEASURED FROM THE LANDING THRESHOLD DOWN THE RWY TO A RIGHT ANGLE TO THE ANTENNA WHEN THE FIRST CHARACTER IS A SPACE.
 *
 * EXAMPLE(S):
 * +00426
 *  00990
 *  14197
 * -12316
 * -00907
 * U
 * NULL
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF NUMBERS 0 -9
 * OR
 * COMBINATIONS OF NUMBERS 0 -9 PRECEDED BY A (-) MINUS OR A (+) PLUS
 * OR A ( ) SPACE
 * OR
 * U, (UNKNOWN)
 * OR
 * NULL
 *
 * ALL NUMERALS ARE PADDED TO 5 POSITIONS.  SEE EXAMPLES IN DEFINITION.
 *
 * SOURCE: SYSTEM GENERATED
 */
public class LocalizerOrGlideSlopeLocation extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 167;
  }

  @Override
  public int fieldCode() {
    return 6;
  }

  @Override
  public String regex() {
    return "(([\\+\\- ]([0-9]{4}[1-9]|[0-9]{3}[1-9][0-9]|[0-9]{2}[1-9][0-9]{2}|[0-9][1-9][0-9]{3}|[1-9][0-9]{4}))|[ ]00000|U|^$)";
  }
}
