package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * A REFERENCE SURFACE CONSISTING OF FIVE QUANTITIES:  THE LATITUDE AND LONGITUDE OF AN INITIAL  POINT, THE AZIMUTH OF A LINE FROM THAT POINT, AND THE PARAMETERS (THE SEMIMAJOR AXIS AND  FLATTENING OR THE SEMI-MAJOR AXIS AND SEMI-MINOR AXIS) OF THE REFERENCE ELLIPSOID.  (JCS AND  DOD GLOSSARY)
 *
 * EXAMPLE(S):
 * TOY
 * WGE
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * CHARACTERS 1-3:  COMBINATIONS OF LETTERS A-Z
 *  OR
 * CHARACTER 1: U OR N
 * CHARACERS 2-3:  BLANK
 *  OR
 *  NULL
 *
 * SOURCE: HOST NATION PUBLICATION
 */
public final class LocalHorizontalDatum extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 3;
  }

  @Override
  public int fieldCode() {
    return 383;
  }

  @Override
  public String regex() {
    return "((ADI|AFG|AIA|AIN|AMA|ANO|ARF|ARS|ASC|ASM|ASQ|ATF|AUA|AUG|BAT|BER|BID|BOO|BUR|CAC|CAI|CAO|CAP|CAZ|CCD|CGE|CHI|CHU|COA|DAL|DID|DOB|EAS|ENW|EST|EUR|EUS|FAH|FLO|FOT|GAA|GEO|GIZ|GRA|GSE|GUA|HEN|HER|HIT|HJO|HKD|HTN|IBE|IDN|IND|INF|INH|IRL|ISG|IST|JOH|KAN|KEA|KEG|KGS|KUS|LCF|LEH|LIB|LUZ|MAS|MER|MID|MIK|MIN|MOD|MPO|MVS|N|NAH|NAP|NAR|NAS|NSD|OEG|OGB|OHA|PHA|PIT|PLN|POS|PRP|PTB|PTN|PUK|PUR|QAT|QUO|REU|SAE|SAN|SAO|SAP|SCK|SGB|SGM|SHB|SIR|SOA|SRL|TAN|TDC|TIL|TOY|TRN|U|VOI|VOR|WAK|WGC|WGE|WGX|YAC|ZAN)?)";
  }
}