package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE ANGULAR DIFFERENCE BETWEEN TRUE NORTH AND MAGNETIC NORTH (GENERAL PLANNING).  MAGNETIC VARIATION OF RECORD IS GENERALLY AN EPOCH YEAR VALUE VALID FOR EVERYTHING ASSOCIATED WITH A GIVEN LOCATION.  THIS VALUE IS ESTABLISHED AT AN AIRPORT AND EVERYTHING REFERENCED BY THAT AIRPORT TO INCLUDE TERMINAL PROCEDURES WILL USE THE SAME VALUE.  THIS VALUE OFTEN GOES UNREVISED FOR MANY YEARS. LAST TWO CHARACTERS WILL BE "65" IF MV_RECORD DATE IS NOT PROVIDED BY SOURCE. TRUE HEADINGS WILL BE OUTPUT AS "E0000" PLUS MAGVAR YEAR.
 *
 * EXAMPLE(S):
 * W018013
 * E008012
 * E000009
 * W000112
 * E002065 (TENTHS UNKNOWN, DATE NOT PROVIDED BY SOURCE)
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * E000000-E180099
 * OR
 * W000100-W179999
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * W179599 = 179 AND FIVE TENTHS OF A DEGREE WEST OF TRUE NORTH.
 *   LAST TWO CHARACTERS INDICATE THE YEAR OF VARIATION (i.e. 99 = 1999).
 *
 * NOTE:  IF NO VARIATION DATE  IS PROVIDED BY SOURCE, THE LAST TWO CHARACTERS WILL BE 65.
 */
public final class MagneticVariationOfRecord extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 7;
  }

  @Override
  public int fieldCode() {
    return 438;
  }

  @Override
  public String regex() {
    return "((E0[0-9]{2}|E1[0-7][0-9]|E180|W0[0-9]{2}|W1[0-7][0-9])[0-9]{3})";
  }
}