package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE MINIMUM ALTITUDE OF THE ATS ROUTE SEGMENT AS DETERMINED BY THE AREA ANALYST BASED ON  HOST NATION INFORMATION.
 *
 * FOR FLIGHT LEVELS SEE DAFIF SPECIFICATION, CHAPTER 3, TERMS AND DEFINITIONS.
 *
 *  THE ALTITUDE CONTAINED IN THE LOW LEVEL ATS ROUTE RECORD (INCLUDING ROUTES THAT ARE BOTH  HIGH AND LOW LEVEL) IS THE MINIMUM FLIGHT ALTITUDE (MFA).
 *
 *  THE MFA IS DEFINED AS THE LOWER LIMIT OF THE ATS UPPER AND LOWER LIMITS (VERTICAL LIMITS)  UNLESS A MINIMUM ALTITUDE THAT IS HIGHER OR LOWER THAN THE LOWER LIMIT IS ESTABLISHED.  IN  CASES WHERE THE HOST NATION COUNTRY FAILS TO IDENTIFY THE MFA OR LOWER LIMIT, NGA WILL  POPULATE AN MFA ASSURING 3000 FT TERRAIN CLEARANCE WITHIN 5 NM OF THE ATS ROUTE CENTERLINE.   THIS DATA WILL COMPARE TO THE CHART DATA WHICH IS INDICATED BY A POUND/NUMBER SIGN (#).
 *
 *  THE MFA POPULATED FOR THE HIGH ALTITUDE ATS ROUTE RECORD IS THE LOWEST USABLE CRUISING  LEVEL OF THE DESIGNATED AIRSPACE UNLESS THE MFA IS HIGHER THAN THE LOWER LIMIT OF THE  DESIGNATED AIRSPACE.  (PS/1FA/005) (DAFIF)
 *
 *  NOTE:  AN ATS ROUTE SEGMENT HAVING BI-DIRECTIONAL CAPABILITY REQUIRES A RECIPROCAL  MINIMUM FLIGHT ALTITUDE (RECIP MFA) FOR THE (E/W) SEGMENT.
 *
 * EXAMPLE(S):
 * 01000
 * 34600
 * FL10
 * FL430
 * NULL
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * 01000 - 99999 (NUMERIC VALUES PADDED WITH LEADING ZEROS)
 * OR
 * FL10 - FL999
 * OR
 * NULL
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 */
public final class MinimumAltitude extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 5;
  }

  @Override
  public int fieldCode() {
    return 186;
  }

  @Override
  public String regex() {
    return "((([0-9][1-9][0-9]{3}|[1-9][0-9]{4})|FL([1-9][0-9]{1,2}))?)";
  }
}