package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE OFFICIAL NAME FOR AN OBJECT (AIRPORT/BOUNDARY/NAVAID/ETC.) DESIGNATED BY THE
 * OPERATING  AGENCY OR IN OFFICIAL PUBLICATIONS OF THE COUNTRY IN WHICH THE OBJECT
 * IS LOCATED SHALL  ALWAYS BE USED.
 *
 *  THE FOLLOWING SPECIFIC RULES WILL APPLY IN THE ORDER LISTED.
 *
 * A.  U.S. MILITARY COMMAND PREFERENCE WILL TAKE PRECEDENCE OVER OTHER SOURCES.
 *
 * B.  NAMES WHICH ARE DERIVED FROM THE ENGLISH TEXT OF A NATIONAL AERONAUTICAL SOURCE ARE  TO BE USED VERBATIM.
 *
 * C. WHEN NAMES ARE DERIVED FROM NATIONAL AERONAUTICAL SOURCE WHICH DOES NOT CONTAIN  ENGLISH TEXT, COORDINATION WITH THE NGA ST. LOUIS/TECHNICAL LIBRARY TRANSLATION SECTION IS
 *  REQUIRED TO ESTABLISH THE SPELLING.
 *
 * D. WHEN THE NAME IS THE SAME AS A GEOGRAPHIC FEATURE OR GEOGRAPHIC PLACE/NAME, AND NONE  OF THE ABOVE SPECIFIED CONDITIONS EXIST, APPLICATION OF BOARD OF GEOGRAPHIC NAMES (BGN)  SPELLING IS REQUIRED.
 *
 *   1. IF NUMERALS ARE REQUIRED, ARABIC NUMERALS SHALL BE USED. NUMERALS ARE NOT PERMITTED AS THE FIRST CHARACTER OF THE AIRPORT/HELIPORT NAME.
 *
 *   2. COMPASS DIRECTIONS OR GEOGRAPHIC TERMS SHALL NOT BE ABBREVIATED.
 *
 *   3. USE OF THE TERM ""NEW"" OR ""OLD"" SHALL BE AVOIDED WHEN ASSIGNING A NAME TO ANY AIRPORT.
 *
 * EXAMPLE(S):
 * AL QAIM, WOODSTOWN
 * PORT MORESBY CTA SCTR A
 * LO-RENINGE UAV AREA
 * MONTREAL/PIERRE  CTLZ"	NAME	A/N	38
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF NUMBERS 0-9, LETTERS A-Z, SPACES AND SPECIAL CHARACTERS
 * OR
 * NULL
 *
 * SOURCE: HOST NATION PUBLICATION
 */
public final class Name extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 38;
  }

  @Override
  public int fieldCode() {
    return 195;
  }

  @Override
  public String regex() {
    return "([\\W\\w]{1,38}|^$)";
  }
}
