package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE IDENTIFICATION (CALL SIGN) ASSIGNED TO A SPECIFIC NAVAID BY THE CONTROLLING AUTHORITY.
 *
 * ILS RECORD:  ILS RECORD FIELDS HAVE A FOUR CHARACTER FIELD LENGTH AND DIFFERENT ALLOWABLES.
 *
 * THOSE MARKERS WITHOUT NAV_IDENTS, OR THOSE IDENTIFIED AS IM, MM, OR OM WILL BE GIVEN AN  IDENT BASED ON THE FOLLOWING PROCEDURE:
 * THE IDENT OF THE ASSOCIATED LOCALIZER FOR THE APPROACH IN WHICH THE MARKER IS ATTACHED,  MINUS THE LEADING "I", WILL BE USED, ADDING A 'I', 'M', OR 'O' TO THE END, DEPENDING ON THE MARKER
 * TYPE.
 *
 * EXAMPLES:
 * LOCALIZER IDENT = IALW
 * MIDDLE MARKER = ALWM
 * OUTER MARKER = ALWO
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF NUMBERS 0-9 AND LETTERS A-Z
 * OR
 * NULL
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * WHEN POPULATING AN AIRPORT IDENT FOR THE MSA CENTER AND THE ANSP DOES NOT PROVIDE AN OFFICIAL ICAO IDENT, THE FAA HOST ID WILL BE POPULATED IN THE NAV IDENT FIELD.
 */
public final class NavaidIdentifier extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 4;
  }

  @Override
  public int fieldCode() {
    return 209;
  }

  @Override
  public String regex() {
    return "(([0-9A-Z]{1,4})?)";
  }
}