package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * "SLAVE" OR "ASSIGNED" VARIATION IS A FIXED VALUE OF MAGNETIC VARIATION APPLIED TO TRUE  DIRECTION TO
 * OBTAIN THE MAGNETIC VALUES FOR RADIALS, COURSES, AND HEADINGS.  THIS IS  ESTABLISHED BY A MECHANICAL
 * ADJUSTMENT TO THE NAVAID EQUIPMENT, AND IS ONLY CHANGED  WHEN SLAVED NORTH VARIES FROM MAGNETIC NORTH
 * BY AN AMOUNT ESTABLISHED BY THE  CONTROLLING AGENCY.
 *
 * LAST FOUR CHARACTERS WILL BE '0165' IF SLAVED_VAR DATE IS NOT PROVIDED BY SOURCE.
 *
 *  EXAMPLES:
 *
 *   W00150210 (W001 30 MIN FEB 2010)
 *   E00200310 (E002 TENTHS UNKNOWN MAR 2010)
 *   W01500165 (W015 TENTHS UNKNOWN DATE NOT PROVIDED BY SOURCE)
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 *  E00000100 - E18001299
 *  OR
 *  W00010100-W17991299
 *  OR
 *  NULL
 *
 *  FIFTH CHARACTER IS A TENTH OF A DEGREE.
 *  THE LAST FOUR CHARACTERS INDICATE THE MONTH AND YEAR OF VARIATION (EX. 0310).
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 *
 * INTENDED USE:
 * WHEN POPULATING THIS FIELD, THE FOLLOWING HIERARCHY OF ANSP VALUES WILL BE FOLLOWED:
 * 1) AIP (ENROUTE SECTION, AD SECTION, TERMINAL PROCEDURE DESIGN MAG VAR),
 * 2) ISOGONIC LINES PROVIDED BY AIP CHARTS,
 * 3) DYNAMIC MAG VAR.
 */
public final class NavaidSlavedVariation extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 9;
  }

  @Override
  public int fieldCode() {
    return 291;
  }

  @Override
  public String regex() {
    return "(((E0[0-9]{3}|E1[0-7][0-9]{2}|E1800|W0[0-9]{2}[1-9]|W0[0-9][1-9][0-9]|W0[1-9][0-9]{2}|W1[0-7][0-9]{2})(0[1-9][0-9]{2}|1[0-2][0-9]{2}))?)";
  }
}