package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE ORGANIZATION PRIMARILY RESPONSIBLE FOR THE TERMINAL PROCEDURE.
 *
 * THE FOLLOWING VALUES ARE DOD APPROVED OFFICES OF PRIMARY RESPONSIBILITY (OPR) AND THE TERMINAL PROCEDURES ARE CODED BY NGA:
 *
 * FAA – FEDERAL AVIATION ADMINSTRATION
 * NGA – NATIONAL GEOSPATIAL-INTELLEGENCE AGENCY
 * USAF – UNITED STATES AIRFORCE
 * USN – UNITED STATES NAVY
 * USA – UNITED STATES ARMY
 * NASA – NATIONAL AERONAUTICS AND SPACE ADMINSTRATION
 * USCG – UNITED STATES COAST GUARD
 *
 * WHEN THE TERMINAL PROCEDURE COMES FROM HOST SOURCE, IS NOT REVIEWED BY AN ABOVE OPR, AND IS CODED BY NGA, THE CODE WILL BE:
 *
 * DNGA
 *
 * WHEN THE TERMINAL PROCEDURE COMES FROM HOST SOURCE, IS NOT REVIEWED BY AN ABOVE OPR, AND IS CODED BY A FIVE-EYE PARTNER, THE CODES WILL BE:
 *
 * AIDU - #1 AERONAUTICAL INFORMATION DOCUMENTS UNIT (UNITED KINGDOM)
 * RAAF - AERONAUTICAL INFORMATION SERVICE - AIR FORCE (AUSTRALIA)
 * DND - DEPARTMENT OF NATIONAL DEFENCE (CANADA)
 * NZDF - NEW ZEALAND DEFENCE FORCE
 *
 * WHEN THE TERMINAL PROCEDURE COMES FROM HOST SOURCE, IS NOT REVIEWED BY AN ABOVE OPR, AND IS CODED BY A COMMERCIAL DATA PROVIDER AND MERGED WITH NGA DATA HOLDINGS, THE CODE WILL BE:
 *
 * COMM
 *
 * WHEN THE VALUE IS A TWO LETTER COUNTRY CODE, THE TERMINAL DATA HAS BEEN CODED BY THE THAT SPECIFIC COUNTRY AND MERGED WITH NGA DATA HOLDINGS.
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * TWO, THREE, OR FOUR LETTER COMBINATIONS OF A-Z
 *
 * SOURCE: DOD PRODUCT SPECIFICATION
 *
 * INTENDED USE:
 * WHEN DETERMINING THE PEDIGREE OF A TERMINAL PROCEDURE IN DAFIF, USE THE ARPT_IDENT TO IDENTIFY THE COUNTRY THE PROCEDURE CAME FROM, THE OPR FIELD TO IDENTIFY WHO IS RESPONSIBLE FOR CODING THE PROCEDURE, AND THE HOST_CTRY_AUTH TO DETERMINE IF THE AIP IS CIVIL OR MILITARY.
 *
 * EXAMPLE 1:
 * ARPT_IDENT = NO91674: THE PROCEDURE WAS DEVELOPED IN NORWAY
 * OPR = AIDU: THE PROCEDURE WAS CODED BY AIDU
 * HOST_CTRY_AUTH = CIV: THE PROCEDURE CAME OUT OF THE CIVIL AIP
 *
 * EXAMPLE 2:
 * ARPT_IDENT = CA25699: THE PROCEDURE WAS DEVELOPED IN CANADA
 * OPR = DNGA: THE PROCEDURE WAS CODED BY NGA
 * HOST_CTRY_AUTH = MIL: THE PROCEDURE CAME OUT OF THE MILITARY AIP
 *
 * EXAMPLE 3:
 * ARPT_IDENT = FR00699: THE PROCEDURE WAS DEVELOPED IN FRANCE
 * OPR = FR: THE PROCEDURE WAS CODED BY THE FRENCH AVIATION AUTHORITY
 * HOST_CTRY_AUTH = MIL: THE PROCEDURE CAME OUT OF THE MILITARY AIP
 */
public final class OfficeOfPrimaryResponsibility extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 4;
  }

  @Override
  public int fieldCode() {
    return 217;
  }

  @Override
  public String regex() {
    return "((A[ACEFGJLMNOQRSTUVY]|B[ABCDEFGHKLMNOPQRSTUVXY]|C[ABDEFGHIJKMNOQRSTUVWY]|D[AJOQR]|E[CGIKNRSTUZ]|F[GIJKMOPQRS]|G[ABGHIJKLMOPQRTVYZ]|H[AKMOQRU]|I[CDMNOPRSTVZ]|J[AEMNOQU]|K[EGNQRSTUVZ]|L[AEGHIOQSTUY]|M[ABCDFGHIJKLNOPQRTUVXYZ]|N[CEFGHILNOPRSUZ]|OD|P[ACEFGKLMOPSU]|QA|R[EIMNOPQSW]|S[ABCEFGHILMNOPTUVWYZ]|T[BDEHIKLNOPSTUVWXZ]|U[CGKPSVYZ]|V[CEIMQT]|W[AEFIQSZ]|YM|ZA|ZI)|DNGA|COMM|NGA|FAA|USN|USAF|USA|NASA|USCG|AIDU|RAAF|DND|NZDF)";
  }
}