package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE VISIBLE MATERIAL OR COMPOSITION OF THE MAJOR PORTION OF THE OVERRUN.
 *
 *  AVAILABLE CODES PERTAINING TO HARD (PERMANENT) SURFACE AND SOFT (NON-PERMANENT) SURFACE  ARE LISTED BELOW.
 * SFC           DESCRIPTION
 * AM2         Metal Planking
 * ASP          ASPHALT, ASPHALTIC CONCRETE, TAR MACADAM, OR BITUMEN BOUND MACADAM (INCLUDING ANY OF THESE SURFACE TYPES WITH CONCRETE ENDS).
 * BIT           BITUMINOUS, TAR OR ASPHALT MIXED IN PLACE, OILED.
 * BRI           BRICK, LAID OR MORTARED.
 * CLA          CLAY.
 * COM        COMPOSITE (LESS THAN 50 PERCENT OF THE RUNWAY LENGTH IS PERMANENT).
 * CON        CONCRETE.
 * COP         COMPOSITE (50 PERCENT OR MORE OF THE RUNWAY LENGTH IS PERMANENT).
 * COR         CORAL.
 * GRE          GRADED OR ROLLED EARTH, GRASS ON GRADED EARTH.
 * GRS          GRASS OR EARTH NOT GRADED OR ROLLED.
 * GVL          GRAVEL.
 * ICE            ICE.
 * LAT           LATERITE.
 * MAC         MACADAM - CRUSHED ROCK WATER BOUND.
 * MEM        MEMBRANE - PLASTIC OR OTHER FIBER MATERIAL.
 * MIX          MIX IN PLACE USING NONBITUMINOUS BINDERS SUCH AS PORTLAND.
 * PEM        PART CONCRETE, PART ASPHALT, OR PART BITUMEN-BOUND MACADAM.
 * PER         PERMANENT, SURFACE TYPE UNKNOWN.
 * PSP         PIERCED STEEL PLANKING.
 * SAN        SAND (GRADED, ROLLED OR OILED).
 * SNO        SNOW.
 * U              SURFACE UNKNOWN.
 *
 * EXAMPLE(S):
 * ASP
 * PEM
 * U
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * AM2, ASP, BIT, BRI, CLA, COM, CON, COP, COR, GRE, GRS, GVL, ICE, LAT, MAC, MEM, MIX, PEM, PER,PSP, SAN, SNO, U
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 */
public final class OverrunSurface extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 3;
  }

  @Override
  public int fieldCode() {
    return 226;
  }

  @Override
  public String regex() {
    return "(AM2|ASP|BIT|BRI|CLA|COM|CON|COP|COR|GRE|GRS|GVL|ICE|LAT|MAC|MEM|MIX|PEM|PER|PSP|SAN|SNO|U)";
  }
}