package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * OVERRUN/STOPWAY IS DEFINED AS A RECTANGULAR AREA ON THE GROUND AT THE END OF THE  RUNWAY, IN THE DIRECTION OF TAKEOFF, PREPARED AS A SUITABLE AREA SO AN AIRCRAFT CAN BE  STOPPED IN CASE OF AN ABANDONED TAKEOFF.
 *
 * RUNWAY OVERRUN LENGTH IS IN FEET.
 *
 * THE LOW END OVERRUN IS THE OVERRUN USED BY AN AIRCRAFT LANDING ON THE RUNWAY LOW END,  AND IS LOCATED BEYOND THE RUNWAY HIGH END PHYSICAL END.  VICE VERSA FOR HIGH END.
 *
 * EXAMPLE(S):
 * 25
 * 4042
 *
 * FIELD TYPE: N
 *
 * ALLOWED VALUES:
 * 25-99999 (LEADING ZEROS ARE SUPPRESSED)
 * OR
 * NULL
 *
 * SOURCE: HOST NATION PUBLICATION OR NGA ORIGINATED
 *
 * INTENDED USE:
 * THIS VALUE MAY BE DERIVED IN THE ABSENSE OF HOST PROVIDED VALUES USING IMAGERY OR MENSURATION TO PROVIDE PRECISE MEASUREMENT FOR THIS FIELD IN ACCORDANCE WITH DO-200B AND DO-201.
 */
public final class OverrunDistance extends DafifInteger {
  @Override
  public int maxFieldLength() {
    return 5;
  }

  @Override
  public int fieldCode() {
    return 225;
  }

  @Override
  public String regex() {
    return "(([1-9][0-9]{2,4}|[3-9][0-9]|2[5-9])?)";
  }
}