package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE ANGULAR DIFFERENCE BETWEEN TRUE NORTH AND MAGNETIC NORTH (GENERAL PLANNING).  PROCEDURE DESIGN MAGVAR IS GENERALLY AN EPOCH YEAR VALUE ESTABLISHED AT AN AIRPORT AND REFERENCED BY INDIVIDUAL TERMINAL PROCEDURES.  THIS VALUE OFTEN GOES UNREVISED FOR MANY YEARS.
 *
 * EXAMPLE(S):
 * E002012
 * W009065
 * NULL
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * E000000-E180099
 *  OR
 *  W000100-W179999
 *  OR
 *  NULL
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * POPULATED WITH CURRENT HOST PLATE/8260-3 MAGNETIC VARIATION.
 *
 * W179599 = 179 AND FIVE TENTHS OF A DEGREE WEST OF TRUE NORTH.
 *   LAST TWO CHARACTERS INDICATE THE YEAR OF VARIATION (i.e. 99 = 1999.
 *
 * NOTE:  IF NO VARIATION DATE  IS PROVIDED BY SOURCE, THE LAST TWO CHARACTERS WILL BE 65.
 */
public final class ProcedureDesignMagvar extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 7;
  }

  @Override
  public int fieldCode() {
    return 451;
  }

  @Override
  public String regex() {
    return "((E0[0-9]{5}|E1[0-7][0-9]{4}|E1800[0-9]{2}|W000[1-9][0-9]{2}|W0[0-9][1-9][0-9]{3}|W0[1-9][0-9][0-9]{3}|W1[0-7][0-9]{4})?)";
  }
}