package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * A ONE CHARACTER FIELD INDICATING WHETHER SHORELINE/HYDROGRAPH FEATURES ARE PRESENT
 * AROUND THE AIRFIELD.  HYDROGRAPH MAY INCLUDE FEATURES WHERE WATER IS A CONSTITUENT PART
 * SUCH AS LAKES (PERENNIAL LAKES), RESERVOIRS, POOLS, STREAMS (FLOW OF WATER EXISTS 	THROUGHOUT
 * THE YEAR), AQUEDUCTS, FLUMES, CONDUITS, CANALS, AND DITCHES.  THE INDICATOR IS 	BASED ON
 * THE DEPICTIONS GENERATED IN THE “TO SCALE” AREA ON TERMINAL INSTRUMENT 	PROCEDURES.
 * (DOD SPECIFICATIONS PS/1FA/004, PS/1FA/091, SECTION 300)
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 *  Y
 * 	OR
 * 	NULL
 *
 * SOURCE: TRANSLATE/FORMAT FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 *
 * THIS FIELD IS NO LONGER MAINTAINED AND WILL BE NULL.
 */
public final class ShorelineHydrography extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 290;
  }

  @Override
  public String regex() {
    return "(^$)";
  }
}
