package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * A CODE WHICH DEFINES THE TYPE OF SEGMENT FOR THE SID, STAR, OR IAP OF WHICH THE RECORD IS AN ELEMENT.
 *
 * SID RECORDS:
 *    1 - SID RUNWAY TRANSITION
 *    2 - SID OR SID COMMON ROUTE
 *    3 - SID ENROUTE TRANSITION
 *    4 - RNAV SID RUNWAY TRANSITION
 *    5 - RNAV SID OR RNAV SID COMMON ROUTE
 *    6 - RNAV ENROUTE TRANSITION
 * NOTE: ICAO TRANSITIONING NAMING CONVENTION FROM RNAV TO RNP SID
 *
 *  STAR RECORDS:
 *    1 - STAR ENROUTE TRANSITION
 *    2 - STAR OF STAR COMMON ROUTE
 *    3 - STAR RUNWAY TRANSITION
 *    4 - RNAV STAR ENROUTE TRANSITION
 *    5 - RNAV STAR OR RNAV STAR COMMON ROUTE
 *    6 - RNAV STAR RUNWAY TRANSITION
 *    7 - PROFILE DESCENT ENROUTE TRANSITION
 *    8 - PROFILE DESCENT OR PROFILE DESCENT COMMON ROUTE
 *    9 - PROFILE DESCENT RUNWAY TRANSITION
 * NOTE: ICAO TRANSITIONING NAMING CONVENTION FROM RNAV TO RNP STAR
 *
 *
 *  IAP RECORDS:
 *    A - APPROACH TRANSITION
 *    B - ILS BACK COURSE
 *    C - ILS CAT II
 *    D - VORDME/VORTAC (BASED ON VORDME OR VORTAC)
 *    E - VOR CIRCLING APPROACH
 *    F - NDB CIRCLING APPROACH
 *    G - RNAV (GPS) (FOR FAA RNP AND ADVANCED RNP). RNAV (GNSS) OR RNP FOR ICAO (REQUIRES ROUTE QUALIFIER 1 OF A,J,P,R,U, OR W, SEE TERM_PAR APCH_RTE_QUAL1)
 *    H - ILS CAT III
 *    I - ILS
 *    J - LAAS-GPS/GLS (PAPP RECORD REQUIRED)
 *    K - WAAS-GPS (PAPP RECORD REQUIRED)
 *    L - ILS LOCALIZER ONLY (NO GS)
 *    M - MLS
 *    N - NDB
 *    O - RNAV (GPS) OVERLAY APPROACH
 *    P - PAR
 *    Q - NDB/DME
 *    R – RNAV (RNP) FOR FAA OR RNP AR FOR ICAO (REQUIRES ROUTE QUALIFIER 1 OF F)
 *    S - VOR (BASED ON VORDME OR VORTAC)
 *    T - TACAN
 *    U - MLS CAT II
 *    V - VOR (NO DME)
 *    W - ADF
 *    X - LDA
 *    Y - SDF
 *    Z - MLS CAT III
 *    1 - RNAV(GPS) PRECISION APPROACH (OTHER)
 *    2 - ILS LOCALIZER ONLY CIRCLING APPROACH
 *    3 - ILS BACK COURSE CIRCLING APPROACH
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * A-Z
 * OR
 * 1-9
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * FOR IAP RECORDS:  G REFERENCES RNAV (GPS) OR (GNSS) PROCEDURES.  R REFERENCES RNAV (RNP) PROCEDURES.
 *
 * STAR CODES 7-9 NOT CURRENTLY IN USE.
 *
 * IAP CODES 1-3 NOT CURRENTLY IN USE.
 */
public final class TerminalApproachType extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 30;
  }

  @Override
  public String regex() {
    return "([1-6ABDEFGILNOQRSTVXY])";
  }
}