package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * ENABLES THE FUNCTION OF A WAYPOINT/FIX AT A SPECIFIC LOCATION TO BE IDENTIFIED.
 * 	VARIOUS FIELDS PROVIDE INFORMATION ON THE FIX.
 *
 * WAYPOINT DESCRIPTION CODE 1:
 * 	A - AIRPORT WAYPOINT
 * 	E - ESSENTIAL WAYPOIT
 * G - RUNWAY OR HELIPAD AS A WAYPOINT
 * 	N - NDB, NDB/DME AS A WAYPOINT
 * P - PHANTOM
 * 	V - VHF NAVAID AS A WAYPOINT
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * A, E, G, N, P, V, NULL
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * WAYPOINT DESCRIPTION CODE 1
 * NOTE:  WHEN WPT_DESC_1 = NAVAID (N, V) – INDICATES WAYPOINT IS COLOCATED WITH A NAVAID.  USE THE WPT FIELDS IN TRM_SEG TO SEARCH THE DAFIF WPT FIELDS TO FIND THE ASSOCIATED DAFIF WAYPOINT.  THE ASSOCIATED DAFIF WAYPOINT WILL CONTAIN THE NAVAID KEY FIELDS.  USE THE NAVAID KEY FIELDS FROM THE DAFIF WPT TABLE TO IDENTIFY THE NAVAID REFERENCED BY THE PROCEDURE.
 *
 * A - AIRPORT AS A WAYPOINT -- WPT_ID WILL EQUAL ICAO.
 *
 * E - ESSENTIAL -- INCLUDES NAMED AND CNF WAYPOINTS.  WPT_NAV_FLAG SHOULD BE NULL.
 *
 * G - RUNWAY AS A WAYPOINT
 *      1)  SID (TYPE 2) WPT_WGS_LAT, WPT_WGS_DLAT, WPT_WGS_LONG, AND WPT_WGS_DLONG REPRESENT RUNWAY THRESHOLD COORDINATES FROM ARPT/RWY.TXT.
 *      2)  IAP (TYPE 3), WPT_WGS_LAT, WPT_WGS_DLAT, WPT_WGS_LONG, AND WPT_WGS_DLONG REPRESENT DISPLACED THRESHOLD COORDINATES IF PRESENT IN SUPP/ADD_RWY.TXT OR RUNWAY THRESHOLD COORDINATES FROM ARPT/RWY.TXT.
 *      3)  USED TO IDENTIFY LANDING THRESHOLD POINTS (LTP) FOR ALL IFPS.
 *
 * N - NDB OR NDB/DME NAVAID USED AS A WAYPOINT.  N INDICATES WPT_ID IS CO-LOCATED WITH A NDB OR NDB/DME NAVAID.  REFERENCE WPT.TXT FOR WPT_NAV_FLAG AND FOR APPLICABLE NAVAID KEY FIELDS.
 *
 * P - PHANTOM WAYPOINT -- A DATABASE WAYPOINT ESTABLISHED DURING PROCEDURE CODING TO FACILITATE MORE ACCURATE NAVIGATION BY THE FMC THAT WOULD BE ALLOWED USING AIR-MASS RELATED PATH TERMINATORS TO REPLICATE SOURCE DATA.  THE WAYPOINT FINDS USE WHEN SUCH CONSIDERATIONS AS INCRESED ENVIRONMENTAL RESTRICTIONS AND THE CONGESTION OF THE AVAILABLE AIRSPACE COME INTO PLAY.  USED TO PERMIT ROUTE CONSTRUCTION WITH TRACK TO FIX (TF) LEGS.  CURRENTLY ONLY USED WHEN SOURCED IN HOST DOCUMENTATION.
 *
 * V - VHF NAVAID AS A WAYPOINT.  V INDICATES WPT_ID IS CO-LOCATED WITH A TYPE 1, 2, 3,4 OR 9 NAVAID.  REFERENCE WPT.TXT FOR WPT_NAV_FLAG FOR APPLICABLE NAVAID KEY FIELDS.  ALTHOUGH TACAN IS A UHF NAVAID IT IS ALSO CONSIDERED A "V" CODE.
 */
public final class TerminalWaypointDescriptionCode1Arpt extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 322;
  }

  @Override
  public String regex() {
    return "((A|E|G|N|P|V)?)";
  }
}