package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * ENABLES THE FUNCTION OF A WAYPOINT/FIX AT A SPECIFIC LOCATION TO BE IDENTIFIED.
 *  VARIOUS FIELDS PROVIDE INFORMATION ON THE FIX.
 *
 * WAYPOINT DESCRIPTION CODE 4:
 *    A - INITIAL APPROACH FIX (IAF)
 *    B - INTERMEDIATE APPROACH FIX (IF)
 *    C - IAF + HOLDING FIX
 *    D - IAF + FACF
 *    F - FINAL APPROACH FIX (FAF)
 *    H - HOLDING FIX
 *    I - FINAL APPROACH COURSE FIX (FACF)
 *    M - MISSED APPROACH POINT
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * A, B, C, D, F, H, I, M
 * OR
 * NULL
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * A-INDICATES INITIAL APPROACH FIX (IAF).
 * B-INDICATES INTERMEDIATE APPROACH FIX (IF).
 * C-INDICATES IAF WITH HOLDING.  USED WHEN IAF HAS ASSOCIATED ARRIVAL HOLDING PATTERN.  HOLDING PATTERN PARAMETERS WILL BE FOUND IN HOLD.TXT FILE.  WHEN C IS USED, THE ASSOCIATED HOLDING PATTERN WILL COINCIDE WITH DUP VALUES OF 5X.
 * D-INDICATES IAF WITH FACF.  ‘D’ WILL ONLY BE CODED WHEN APPROACH TYPE IS NOT EQUAL TO 'A' FOR PROC TYPE 3.
 * F-INDICATES FINAL APPROACH FIX (FAF).  FIX PUBLISHED AS FAF OR FAP BY GOVERNMENT SOURCE.
 * H-INDICATES HOLDING FIX -- HOLDING PATTERN ASSOCIATED WITH CODED WPT_ID.  HOLDING PATTERN PARAMETERS WILL BE FOUND IN HOLD.TXT FILE.
 * I-INDICATES FINAL APPROACH COURSE FIX (FACF).  MAY BE A FIX PUBLISHED AS THE FACF BY GOVERNMENT SOURCE OR WHEN NOT PUBLISHED, YET REQUIRED, PROVIDED BY DATA SUPPLIER.
 * M-INDICATES THE PUBLISHED MISSED APPROACH POINT FIX.
 */
public final class TerminalWaypointDescriptionCode4 extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 353;
  }

  @Override
  public String regex() {
    return "((A|B|C|F|D|H|I|M)?)";
  }
}