package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * ENABLES THE FUNCTION OF A WAYPOINT/FIX AT A SPECIFIC LOCATION TO BE IDENTIFIED.
 * VARIOUS FIELDS PROVIDE INFORMATION ON THE FIX.
 *
 * WAYPOINT DESCRIPTION CODE 3:
 * A - UNNAMED STEPDOWN WAYPOINT AFTER THE FAF
 * B - UNNAMED STEPDOWN WAYPOINT BEFORE THE FAF
 * M - FIRST LEG OF MISSED APPROACH
 * S - NAMED STEPDOWN WAYPOINT
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * A, B, M, S, NULL
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 *  A-INDICATES UNNAMED STEP-DOWN FIX AFTER FINAL APPROACH FIX (FAF).  WPT.TXT/TYPE='I' (PUBLISHED FIX, BUT NOT NAMED IN GOVERNMENT SOURCE).
 *
 * B-INDICATES UNNAMED STEP-DOWN FIX BEFORE FINAL APPROACH FIX (FAF).  WPT.TXT/TYPE='I' (PUBLISHED FIX, BUT NOT NAMED IN GOVERNMENT SOURCE).
 *
 * M-INDICATES FIRST LEG OF MISSED APPROACH PROCEDURE.
 *
 * S-INDICATES NAMED STEP-DOWN FIX.  ANY WAYPOINT ESTABLISHED AND NAMED BY GOVERNMENT SOURCE BETWEEN FAF AND MAP OR BETWEEN PUBLISHED FINAL APPROACH COURSE FIX (FACF) AND FAF.
 */
public final class TerminalWaypointDescriptionCode3 extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 1;
  }

  @Override
  public int fieldCode() {
    return 352;
  }

  @Override
  public String regex() {
    return "((A|B|M|S)?)";
  }
}