package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE TERM IDENT INCLUDES THE COMPUTER IDENTIFICATION CODE WHICH CAN BE UP TO 6 CHARACTERS (POSITIONS 1-6); AN EMBEDDED SPACE AT POSITION 7; AND THE FULL TERM IDENT NAME (POSITIONS 8-28). WHEN THE FULL TERM IDENT NAME IS LONGER THAN 21 CHARACTERS, THE FOLLOWING RULES ARE USED:
 *
 * A) ELIMINATE WORDS OR ABBREVIATIONS SUCH AS "DEPARTURE" AND "ARRIVAL"
 * B) ELIMINATE CITY NAMES AND NAMES OF AIRPORTS OR HELIPORTS WHEN USED AS PART OF A PROCEDURE NAME.
 * C) NUMBERS WILL ALWAYS BE DISPLAYED AS INTEGERS (EX. THREE BECOMES "3").
 * D) THE IDENTIFIER FOR STANDARD TERMINAL ARRIVALS WILL BE THE FILE CODE (EX. GILMORE SIX ARRIVAL: GQE.GQE6 BECOMES GQE6).
 * E) THE ABBREVIATION FOR RUNWAY (RWY) IS RW (EX.  RWY 34 BECOMES RW34).
 *    1) SIDS AND STARS (PROCEDURE TYPE 1 AND 2):  STANDARD FORMAT WILL BE THE PROCEDURE IDENT OR COMPUTER CODE (INCLUDING THE SUFFIX NUMBER) IN THE FIRST SIX POSITIONS FOLLOWED BY THE COMPLETE PROCEDURE NAME IN POSTIONS 8 THROUGH 28.  IT IS NOT NECESSARY TO USE ALL 6 POSITIONS FOR THE IDENT OR ALL 21 POSITIONS FOR THE NAME.  IF THE PROCEDURE NAME IS EXACTLY THE SAME AS THE PROCEDURE IDENT, THE NAME WILL BE OMITTED.
 * IF NO IDENT IS PROVIDED:
 * - IF THE NAME IS SIX CHARACTERS OR LESS, USE THE FULL NAME.
 * - IF THE NAME IS GREATER THAN SIX CHARACTERS, TRUNCATE FROM RIGHT TO LEFT TO SIX POSITIONS, RETAINING THE SUFFIX NUMBER IF INDICATED.
 *
 * EXAMPLES:
 * - LARK ONE ARRIVAL (LARKS.LARK1) BECOMES:  LARKS1
 * - COMPTON3X BECOMES:  COM3X   COMPTON3X
 * - ALBER1G BECOMES:  ALB1G   ALBER1G
 *
 * THE SIXTH POSITION CAN BE USED FOR MULTIPLE INDICATORS:
 * - SIGONELLA SIG11 (NSY) BECOMES:   SIG111   SIGONELLA SIG11 (NSY)
 * - SIGONELLA SIG11 (SIG) BECOMES:   SIG112   SIGONELLA SIG11 (SIG)
 *
 *     2) APPROACH (PROCEDURE TYPE 3): THE FIRST FIVE CHARACTERS ARE RESERVED FOR THE COMPUTER IDENT. THE FIRST CHARACTER IS THE SEGMENT TYPE (EX. I = ILS, V = VOR, N = NDB, E = VOR CIRCLING).
 *
 * RUNWAY DEPENDENT PROCEDURES
 * CHARACTER POSITION AND CONTENTS:
 *         1) APPROACH TYPE, ALLOWABLE VALUES: B,C,D,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,1 (SEE FIELD DEFINITION #30 TERMINAL APPROACH TYPE FOR DETAILS)
 *         2-3) RUNWAY IDENTIFIERS (NUMERIC CHARACTERS IN TENS OF DEGREES, ALLOWABLE RANGE IS 01-36)
 *          4) RUNWAY DESIGNATION, ALLOWABLE VALUES:
 *              -(DASH) PLACEHOLDER
 *              L - LEFT
 *              R - RIGHT
 *              C - CENTER
 *              SPACE
 *          5) ALPHANUMERIC Multiple Indicator Range:
 *              1-9 or A-Z
 *               SPACE
 * NOTE: "C" Can Mean Approach Category C OR C AND D (CAT CD) or COPTER. COPTER/CPTR will be listed in characters 8-13 of the entire TRM_IDENT string.
 *          6) SPACE
 *
 * CIRCLE TO LAND PROCEDURES
 * CHARACTER POSITION AND CONTENTS
 * 1) APPROACH TYPE. ALLOWABLE VALUES: E,F,G,L,N,Q,2,3 (SEE FIELD DEFINITION #30 TERMINAL APPROACH TYPE FOR DETAILS)
 * 2-4) IAP IDENT, 3 ALPHA CHARACTERS: VOR, LOC, GPS, BCL, LDA, SDF, NDB, TAC
 * 5) AMMENDMENT SUFFIX, A-Z OR 1-9
 * 6) SPACE
 *
 * HELICOPTER APPROACH PROCEDURES TO FINAL APPROACH COURSE
 * CHARACTER POSITION AND CONTENTS
 * 1) APPROACH TYPE ALLOWABLE VALUES: B,C,D,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z, 1,2,3 (SEE FIELD DEFINITION #30 TERMINAL APPROACH TYPE FOR DETAILS)
 * 2-4) THREE DIGIT COURSE DESIGNATION OR PROCEDURE FINAL APPROACH COURSE
 * 5) AMMENDMENT SUFFIX-1 ALPHANUMERIC: A/B/C/D/1/2/3 ETC OR SPACE
 * 6) SPACE
 * HELICOPTER APPROACH PROCEDURES TO HELIPORTS AND CODED TO A SPECIFIC PAD IDENTIFIER
 * CHARACTER POSITION AND CONTENTS
 * 1) APPROACH TYPE ALLOWABLE VALUES: B,C,D,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z, 1,2,3 (SEE FIELD DEFINITION #30 TERMINAL APPROACH TYPE FOR DETAILS)
 * 2-6) PAD IDENTIFICATION
 *
 * NOTES:
 * 1) FOR POSITIONS 1-6 SPACES ARE ONLY ALLOWED AFTER TERM IDENT CHARACTERS
 * 2) THE FIFTH POSITION IS RESERVED FOR MULTIPLE INDICATORS IN TYPE 3 IAPS.
 * 3) IF THERE IS NO RWY DESIGNATOR L, R, OR C, AND A MULTIPLE INDICATOR IS REQUIRED, THEN THE FOURTH POSITION WILL BE POPULATED WITH A DASH.
 *
 * EXAMPLES:
 * - VOR-A BECOMES:  EVORA   VOR-A
 * - HI-VOR/DME RWY13R BECOMES:  D13R   HI VORDME RW13R
 * - ILS RWY24R BECOMES:  I24R   ILS RW24R (CAT II)
 * - VOR/DME RWY 07 (CAT C&amp;D) BECOMES:  D07   VORDME RW07 (CATCD)
 * - VOR/DME 004 BECOMES:  E004   VORDME 004
 * - COPTER TACAN 304 BECOMES:  T304   COPTER TACAN 304
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF NUMBERS 0-9, LETTERS A-Z, SPACES AND SPECIAL CHARACTERS
 *
 * RESTRICTIONS:
 * 1) FOR POSITIONS 1-6 SPACES ARE ONLY ALLOWED AFTER TERM IDENT CHARACTERS
 * 2) POSITION 7 IS ALWAYS AN EMBEDDED SPACE
 * 3) THE PROCEDURE NAME WILL ALWAYS BEGIN WITH POSITION EIGHT REGARDLESS OF THE NUMBER OF POSITIONS USED FOR THE COMPUTER IDENT CODE
 * 4) IF POSITION 8 OR GREATER NEEDS TO BE POPULATED, POSITION 8 SHALL NOT BE A SPACE
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 */
public final class TerminalIdentifier extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 28;
  }

  @Override
  public int fieldCode() {
    return 312;
  }

  @Override
  public String regex() {
    return "([A-Z0-9\\- ]{1,6}[ ][A-Z0-9\\/\\(\\)\\- ]{0,21}|[A-Z0-9\\- ]{1,6})";
  }
}