package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * THE ANGULAR DIFFERENCE BETWEEN TRUE NORTH AND MAGNETIC NORTH.
 *
 * "SLAVE" OR "ASSIGNED" VARIATION IS A FIXED VALUE OF MAGNETIC VARIATION APPLIED TO TRUE  DIRECTION TO OBTAIN THE MAGNETIC VALUES FOR RADIALS, COURSES, AND HEADINGS.  THIS IS  ESTABLISHED BY A MECHANICAL ADJUSTMENT TO THE NAVAID EQUIPMENT, AND IS ONLY CHANGED  WHEN SLAVED NORTH VARIES FROM MAGNETIC NORTH BY AN AMOUNT ESTABLISHED BY THE  CONTROLLING AGENCY.
 *
 * EXAMPLE(S):
 * 2.217460
 * -7.060340
 * -3.000000
 * 21.452497
 *
 * FIELD TYPE: N
 *
 * ALLOWED VALUES:
 * -179.999999 - 180.000000 (TRAILING ZEROS ARE NOT TRIMMED--ALWAYS SIX NUMERICS TO THE RIGHT OF THE DECIMAL)
 *  OR
 *  NULL
 *
 * SOURCE: HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * FOR NAV1_MVAR AND NAV2_MVAR THIS VALUE IS SOURCED FROM THE SLAVE VAR OF THE CORRESPONDING NAVAID WHEN PROVIDED BY THE ANSP. FOR NAVAID TYPE 5,7, 9 AND ILS COMPONENT TYPE D, THE DYNAMIC MAGVAR IS USED FOR DAFIF OUTPUT BECAUSE THEY DO NOT HAVE A SLAVE VAR.
 */
public final class TerminalNavaidSlaveVariation extends DafifDouble {
  @Override
  public int maxFieldLength() {
    return 11;
  }

  @Override
  public int fieldCode() {
    return 182;
  }

  @Override
  public String regex() {
    return "(((\\-)?([0-9]|[1-9][0-9]|1[0-7][0-9])\\.[0-9]{6}|180.000000)?)";
  }
}