package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * DEFINES THE TRACK GEOMETRY FOR A SINGLE TERMINAL SEGMENT RECORD.  ALSO CALLED PATH  TERMINATOR(S)
 *
 * AF - CONSTANT DME ARC TO A FIX
 *  CA - COURSE TO AN ALTITUDE (POSITION UNSPECIFIED)
 *  CD - COURSE TO A DME DISTANCE
 *  CI - COURSE TO A NEXT LEG FOLLOWED BY A COURSE ORIENTED LEG (INTERCEPT POINT UNDEFINED)
 *  CF - COURSE TO A FIX
 *  CR - COURSE TO A RADIAL TERMINATION (INTERCEPT POINT UNDEFINED)
 *  DF - COMPUTED TRACK DIRECT TO A FIX
 *  FA - COURSE FROM A FIX TO AN ALTITUDE
 *  FC - COURSE FROM A FIX TO A DISTANCE
 * FD-COURSE FROM A FIX TO A DME DISTANCE (8.1 ONLY)
 *  FM - COURSE FROM A FIX TO A MANUAL TERMINATION
 *  IF - INITIAL FIX
 *  PI - PROCEDURE TURN FOLLOWED BY A COURSE TO A FIX (CF)
 * RF-CONSTANT RADIUS TO A FIX (8.1 ONLY)
 *  TF - TRACK BETWEEN TWO FIXES (GREAT CIRCLE)
 *  VA - HEADING TO AN ALTITUDE (POSITION UNSPECIFIED)
 *  VD - HEADING TO A DME DISTANCE
 *  VI - HEADING TO A NEXT LEG (INTERCEPT POINT UNDEFINED)
 *  VM - HEADING TO A MANUAL TERMINATION
 *  VR - HEADING TO A RADIAL TERMINATION (INTERCEPT POINT UNDEFINED)
 *
 *  HOLDING PATTERNS:
 *  HF - AUTOMATICALLY AT THE FIX AFTER ONE FULL PATTERN
 *  HA - AUTOMATICALLY AT A FIX AFTER REACHING AN ALTITUDE
 *  HM - MANUALLY
 *
 * NOTE:  THE PI – CF SEQUENCE IS UNIQUE.  THE PI LEG CONTAINS A MAGNETIC COURSE WITH 45 DEGREES  DIVERGENCE FROM THE OUTBOUND COURSE.  DISTANCE IS MAXIMUM EXCURSION DISTANCE.  FIX1  BEARING IS THE OUTBOUND COURSE FROM THE RECOMMENDED NAVAID.  FIX1 DISTANCE IS THE DISTANCE  FROM THE RECOMMENDED NAVAID.  CF LEG (IF USED) IS THE MAGNETIC COURSE TO THE WAYPOINT OR  NAVAID.  DISTANCE IS ONE-HALF THE DISTANCE IN THE PI LEG DISTANCE FIELD.
 *
 *  NOTE:  THE TRACK DESCRIPTION CODE DETERMINES WHAT DATA IS REQUIRED.  SEE DAFIF PRODUCT  SPECIFICATION APPENDIX D CHART FOR REQUIRED AND OPTIONAL FIELDS.  OPTIONAL FIELDS SHALL BE  POPULATED IF DATA IS AVAILABLE.
 *
 * FIELD TYPE: A
 *
 * ALLOWED VALUES:
 * AF, CA, CD, CF, CI, CR, DF, FA, FC, FD,  FM, HA, HF, HM, IF, PI, RF, TF, VA, VD, VI, VM, VR
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 *
 * INTENDED USE:
 * ARINC DEFINITIONS
 * DEFINES THE TRACK GEOMETRY FOR A SINGLE TERMINAL SEGMENT RECORD.  ALSO CALLED PATH TERMINATOR(S).
 *
 * AF – DEFINES A TRACK OVER GROUND AT SPECIFIED CONSTANT DISTANCE FROM A DATABASE DME NAVAID.
 * CA – DEFINES A SPECIFIED COURSE TO A SPECIFIC ALTITUDE AT AN UNSPECIFIED POSITION.
 * CD – DEFINES A SPECIFIC COURSE TO A SPECIFIC DME DISTANCE WHICH IS FROM A SPECIFIC DATABASE DME NAVAID.
 * CI – DEFINES A SPECIFIED COURSE TO INTERCEPT A SUBSEQUENT LEG.
 * CF – DEFINES A SPECIFIED COURSE TO A SPECIFIC DATABASE FIX.
 * CR – DEFINES A COURSE TO A SPECIFIED RADIAL FROM A SPECIFIC DATABASE VOR OR TACAN NAVAID.
 * DF – DEFINES AN UNSPECIFIED TRACK STARTING FROM AN UNDEFINED POSITION TO A SPECIFIC DATABASE FIX.
 * FA – DEFINES A SPECIFIED TRACK OVER GROUND FROM A DATABASE FIX TO A SPECIFIED ALTITUDE AT AN UNSPECIFIED POSITION.
 * FC – DEFINES A SPECIFIED TRACK OVER GROUND FROM A DATABASE FIX FOR A SPECIFIC DISTANCE.
 * FD – DEFINES A SPECIFIED TRACK OVER GROUND FROM A DATABASE FIX TO A SPECIFIC DME DISTANCE WHICH IS FROM A SPECIFIC DATABASE DME NAVAID.
 * FM – DEFINES A SPECIFIED TRACK OVER GROUND FROM A DATABASE FIX UNTIL MANUAL TERMINATION OF THE LEG.
 * IF – INITIAL FIX – DEFINES A DATABASE FIX AS A POINT IN SPACE.
 * PI – DEFINES A COURSE REVERSAL STARTING AT A SPECIFIC DATABASE FIX, INCLUDES OUTBOUND LEG FOLLOWED BY A LEFT OR RIGHT TURN AND 180 DEGREE COURSE REVERSAL TO INTERCEPT THE NEXT LEG.  A MAXIMUM EXCURSION DISTANCE IS INCLUDED AS A DATA FIELD.
 * RF – DEFINES A CONSTANT RADIUS TURN BETWEEN TWO DATABASE FIXES, LINES TANGENT TO THE ARC AND A CENTER FIX.
 * TF – DEFINES A GREAT CIRCLE TRACK OVER GROUND BETWEEN TWO KNOWN DATABASE FIXES.
 * VA – DEFINES A SPECIFIED HEADING TO A SPECIFIC ALTITUDE TERMINATION AT AN UNSPECIFIED POSITION.
 * VD – DEFINES A SPECIFIED HEADING TERMINATING AT A SPECIFIED DME DISTANCE FROM A SPECIFIC DATABASE DME NAVAID.
 * VI – DEFINES A SPECIFIED HEADING TO INTERCEPT THE SUBSEQUENT LEG AT AN UNSPECIFIED POSITION.
 * VM – DEFINES A SPECIFIED HEADING UNTIL A MANUAL TERMINATION.
 * VR – DEFINES A SPECIFIED HEADING TO A SPECIFIED RADIAL FROM A SPECIFIC DATABASE VOR OR TACAN NAVAID.
 *
 * HA, HF, HM:
 * DEFINE A HOLDING PATTERN IN LIEU OF PROCEDURE TURN COURSE REVERSAL OR A TERMINAL PROCEDURE REFERENCED MANDATORY HOLDING PATTERN AT A SPECIFIED DATABASE FIX.  LEG DISTANCE IS INCLUDED AS A DATA FIELD. THE THREE CODES INDICATE DIFFERENT PATH TERMINATION TYPES:
 * HA = ALTITUDE TERMINATION.
 * HF = SINGLE CIRCUIT TERMINATING AT THE FIX.
 * HM = MANUAL TERMINATION.
 *
 * NOTE:  EACH TRACK DESCRIPTION CODE HAS DIFFERENT DATA REQUIREMENTS.  SEE DAFIF PRODUCT SPECIFICATION APPENDIX D CHART FOR REQUIRED AND OPTIONAL FIELDS.  OPTIONAL FIELDS MAY BE POPULATED WHEN SOURCED.
 */
public final class TrackDescriptionCode extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 2;
  }

  @Override
  public int fieldCode() {
    return 318;
  }

  @Override
  public String regex() {
    return "(AF|CA|CD|CF|CI|CR|DF|FA|FC|FD|FM|HA|HF|HM|IF|PI|RF|TF|VA|VD|VI|VM|VR)";
  }
}