package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * A.  THE UNABBREVIATED NAME OF A NAMED WAYPOINT AND, WHEN APPLICABLE, THE   BEARING/DISTANCE FROM THE NAVAID FORMING THE WAYPOINT.
 *
 * EXAMPLE(S):
 * BATHURST
 * NEWCASTLE
 * (DUB 327/124)
 * (EAS 198/I-SN 005.6)
 *
 *
 * EXAMPLE:  LITOSS OR LITOSS (LJS 138/027) WHERE 138 IS THE OUTBOUND BEARING FROM THE NAVAID AND 027 IS DISTANCE FROM THE NAVAID TO THE WAYPOINT.
 *
 *  B.  COMPUTER NAVIGATION FIX (CNF) IS A POINT IDENTIFIED IN REFERENCE TO COMPUTER FLIGHT  PLANNING BUT IS NOT USED FOR ANY AIR TRAFFIC CONTROL FUNCTIONS.  FURTHER DESCRIPTION OF A CNF  WAYPOINT IS INDICATED IN THE FOLLOWING:
 *
 *  EXAMPLES:
 *   NAME PROVIDED BY HOST COUNTRY
 *    EXAMPLE:  DOBOO ENTER AS (DOBOO)
 *
 *    NAME NOT PROVIDED BY HOST COUNTRY
 *      1.  CNF WAYPOINT FORMED BY NAVAID (BEARING/DISTANCE)
 *        EXAMPLE: (LJS 138/027)
 *
 *      2.  TWO CNF WAYPOINTS FORMED BY NAVAID (BEARING/DISTANCE) (WAYPOINTS SAME DISTANCE FROM NAVAID).
 *        EXAMPLE:  (INK 090/020) (INK 270/020)
 *
 *      3.  CNF WAYPOINT WHEN ACCURATE NAVAID BEARING INFORMATION IS NOT AVAILABLE
 *      (DISTANCE 135 IS AN ACCUMULATIVE MILEAGE ALONG THE ATS ROUTE SEGMENTS FROM THE NAVAID TO THE WAYPOINT).
 *        EXAMPLE:  (PAZ/135)
 *
 *        NOTE:  WAYPOINT INCLUDES MILEAGE BREAKDOWN SYMBOL.
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * COMBINATIONS OF NUMBERS 0-9, LETTERS A-Z, SPACES AND SPECIAL CHARACTERS
 *  OR
 *  NULL
 *
 * SOURCE: TRANSLATED/FORMATTED FROM HOST NATION PUBLICATION
 */
public final class WaypointDescriptionName extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 25;
  }

  @Override
  public int fieldCode() {
    return 92;
  }

  @Override
  public String regex() {
    return "(([\\WA-Z0-9]{1,25})?)";
  }
}