package org.mitre.tdp.boogie.dafif.v81.field;

/**
 * CONTAINS THE NAME (INCLUDES NAVAID IDENT) OR SERIES OF CHARACTERS WITH WHICH THE WAYPOINT  IS IDENTIFIED.
 *
 *  WAYPOINT IDENTIFIERS ARE ASSIGNED TO ALL WAYPOINTS IN ACCORDANCE WITH THE FOLLOWING  RULES:
 *
 *  A. NAVAID FACILITIES:  A WAYPOINT CO-LOCATED WITH A NAVAID WILL TAKE ON THE OFFICIAL 2, 3, OR 4  CHARACTER IDENTIFIER OF THE NAVAID FACILITY.
 *    EXAMPLES:
 *      LOS ANGELES VORTAC - LAX
 *      TYNDALL TACAN - PAM
 *      RIGA ENGURE, LITHUANIA - AN
 *
 * B.  WAYPOINT IDENTIFIERS SHOULD BE DEVELOPED USING THE FOLLOWING RULES SEQUENTIALLY UNTIL  FIVE-CHARACTER (OR FEWER) GROUPS EMERGE.
 *
 * 1. ONE-WORD NAMES:
 *        A.  USE THE FULL NAME IF FIVE OR LESS CHARACTERS ARE INVOLVED.
 *                EXAMPLES:
 *                  ACRA, LOGAN, PIKE, DOT
 *
 *        B.  ELIMINATE DOUBLE LETTERS
 *               EXAMPLES:
 *                 KIMMEL BECOMES KIMEL
 *                 COTTON BECOMES COTON
 *                 RABBIT BECOMES RABIT
 *
 *        C.  KEEP THE FIRST LETTER, FIRST VOWEL AND LAST LETTER, DROP OTHER  VOWELS STARTING FROM RIGHT TO LEFT.
 *               EXAMPLES:
 *                 ADOLPH BECOMES ADLPH
 *                 BAILEY BECOMES BAILY
 *                 BURWELL BECOMES BURWL
 *
 *         D.  DROP CONSONANTS, STARTING FROM RIGHT TO LEFT
 *                EXAMPLES:
 *                  ANDREWS BECOMES ANDRS
 *                  BRIDGEPORT BECOMES BRIDT
 *
 * 2.  MULTIPLE WORD NAMES:
 *  USE THE FIRST LETTER OF THE FIRST WORD AND ABBREVIATE THE LAST WORD USING THE ABOVE RULES  FOR ONE-WORD NAMES TO REDUCE TO FOUR CHARACTERS.
 *    EXAMPLES:
 *      CLEAR LAKE BECOMES CLAKE
 *      ROUGH AND READY BECOMES RREDY
 *
 *  3.  PHONETIC LETTER NAMES:
 *  WHEN AN ICAO PHONETIC ALPHA CHARACTER IS USED AS A WAYPOINT NAME (ALPHA, BRAVO, CHARLIE,  ETC.), USE THE EQUIVALENT LETTER (A, B, C, ETC.) FOLLOWED BY A MINUS (-) SIGN AND THE TWO LETTER
 *  ICAO CODE FOR THE COUNTRY IN WHICH THE WAYPOINT HAS AN IDENTIFICATION CODE.  WHEN MORE  THAN ONE WAYPOINT IN A COUNTRY HAS THE SAME PHONETIC NAME, OBTAIN UNIQUENESS BY ADDING  A NUMERIC CHARACTER AFTER THE ICAO CODE.
 *    EXAMPLES:
 *      WAYPOINT ALPHA IN FRANCE BECOMES A-LF
 *      FIRST WAYPOINT ECHO IN ENGLAND BECOMES E-EG1
 *      SECOND WAYPOINT ECHO IN ENGLAND BECOMES E-E2
 *
 *  WHEN A DOUBLE PHONETIC SUCH AS 'TANGO INDIA' IS USED AS THE WAYPOINT NAME, PUT THE TWO  LETTERS REPRESENTED BY THE PHONETICS AHEAD OF THE MINUS SIGN AND ICAO CODE.
 *    EXAMPLE:
 *      WAYPOINT TANGO INDIA IN MEXICO BECOMES TI-MM
 *
 *  4.  DUPLICATE IDENTIFIERS:
 *  SHOULD APPLICATION OF THESE RULES RESULT IN MORE THAN ONE WAYPOINT HAVING THE SAME  IDENTIFIER, A NEW IDENTIFIER SHOULD BE GENERATED FOR EACH WAYPOINT BY DEVELOPING A FOUR
 *  (OR LESS) CHARACTER IDENTIFIER AND ADDING A SUFFIX NUMBER OR LETTER.
 *    EXAMPLES:
 *      SHAWNEE (COLO) SHAE1
 *      SHAWNEE (CAL) SHAE2
 *
 * IF THE SUFFIX NUMBER REACHES 10, START OVER WITH ONE AND PLACE THE SUFFIX IN THE FOURTH  CHARACTER POSITION.  THE ORIGINAL FOURTH CHARACTER SHOULD BE PLACED IN THE FIFTH CHARACTER  POSITION.
 *    EXAMPLE:  SHAWNEE (OKLA) SHA1E
 *
 * 5.  NO NAME ASSIGNED:
 *  IF NO NAME IS ASSIGNED, SHOW THE NAVAID IDENT AND DISTANCE FROM THAT NAVAID.
 *  EXAMPLES:  AA 1 BECOMES AA001
 *  EXAMPLES:  AA 10 BECOMES AA010
 *  EXAMPLES:  AA 200 BECOMES AA200
 *  EXAMPLES:  MAC 50 BECOMES MAC50
 *  EXAMPLES:  MAC 200 BECOMES 00MAC
 *
 *  6.  NDB WAYPOINT:
 *  NDB WAYPOINTS WILL END IN 'NB' IF THE NDB NAVAID HAS THE SAME IDENT AS ANOTHER NAVAID  FACILITY IN THE COUNTRY 'U.S.'.  FOR AN NDB WITH TWO CHARACTER IDENTS OR LESS (LOCATORS), THE
 *  COLLOCATED WAYPOINT IDENT WILL HAVE THE NAVAID NAME VICE THE NAVAID IDENT.
 *    EXAMPLE:  NAV ID=FL, WPT ID=ALCOT
 *
 *  FOR COUNTRIES NOT DESIGNATED AS 'U.S.', WHEN AN NDB HAS A FIVE CHARACTER OR LESS DESCRIPTOR  NAME, THE NAME MAY BE USED VICE THE NAV IDENT.
 *    EXAMPLE:
 *      ID=X WPT=XRAYE (XRAY AT EDMONTON)
 *
 * 7.  TERMINAL WAYPOINTS:
 * FOR A RUNWAY FIX (WPT_DESC_1=G) WPT_ID WILL BE THE RWY IDENT (RW24L, RW34).
 *
 *  INCLUDES MULTIPLE DIFFERENT TYPE NAVAIDS WITH THE SAME IDENTS, SAME COUNTRY.
 *    EXAMPLES:
 *      HMN
 *      HMNNB (NDB)
 *      HMNV (VOR)
 *      HMNT (TACAN)
 *
 *  TERMINAL PROCEDURES WITH A MULTIPLE BEARING/RADIAL REFERENCED ON DME ARCS WILL BE  IDENTIFIED WITH A BEARING/RADIAL WITH EITHER THE FIRST TWO NUMBERS OF THE BEARING/RADIAL OR
 *   LAST TWO OF THE BEARING/RADIAL STARTING IN THE NORTH CLOCKWISE.
 *    EXAMPLES:
 *      BEARING/RADIAL IDENT
 *      HAA 121                HAA12
 *      HAA 126                HAA26
 *      HAA 128                HAA28
 *      HAA 228                HAA22
 *
 *
 *  8.  REPORTING POSITIONS DEFINED BY COORDINATES.  (ARINC 424)
 *  (POINTS WITHIN OCEANIC CONTROL AREAS)
 *
 *  LATITUDE PRECEDES LONGITUDE:
 *    USE SINGLE CHARACTER TO PROVIDE BOTH LAT/LONG INFORMATION
 *      N – NORTH LAT AND WEST LONG
 *      E – NORTH LAT AND EAST LONG
 *      S – SOUTH LAT AND EAST LONG
 *      W – SOUTH LAT AND WEST LONG
 *
 *  FULL DEGREE OF LATITUDE (SEE THIRD OR FIFTH POSITION FOR INDICATOR):
 *  NORTH LAT/WEST LONG – LONG LESS THAN 100 DEG
 *      N5200/W07500 – 5275N
 *  NORTH LAT/WEST LONG – LONG EQUAL TO OR GREATER THAN 100 DEG
 *      N7500/W17000 – 75N70
 *  NORTH LAT/EAST LONG – LONG LESS THAN 100 DEG
 *      N5000/E02000 – 5020E
 *  NORTH LAT/EAST LONG – LONG EQUAL TO OR GREATER THAN 100 DEG
 *      N7500/E15000 – 75E50
 *  SOUTH LAT/WEST LONG – LONG LESS THEN 100 DEG
 *      S5200/W07500 – 5275W
 *  SOUTH LAT/WEST LONG – LONG EQUAL TO OR GREATER THAN 100DEG
 *      S7500/W17000 – 75W70
 *  SOUTH LAT/EAST LONG – LONG LESS THAN 100 DEG
 *      S5000/E02000 – 5020S
 *  SOUTH LAT/EAST LONG – LONG EQUAL TO OR GREATER THAN 100 DEG
 *      S7500/E15000 – 75S50
 *
 *  HALF DEGREE OF LATITUDE (SEE FIRST OR SECOND CHARACTER POSITION FOR INDICATOR):
 *  NORTH LAT/WEST LONG – LONG LESS THAN 100 DEG
 *      N5630/W02000 – N5620
 *      N5030/W04000 – N5040
 *  NORTH LAT/WEST LONG – LONG EQUAL TO OR GREATER THAN 100 DEG
 *      N7530/W17000 – 7N570
 * NORTH LAT/EAST LONG – LONG LESS THAN 100 DEG
 *      N5030/E02000 – E5020
 *  NORTH LAT/EAST LONG – LONG EQUAL TO OR GREATER THAN 100 DEG
 *      N7530/E15000 – 7E550
 *  SOUTH LAT/WEST LONG – LONG LESS THEN 100 DEG
 *      S5230/W07500 – W5275
 *  SOUTH LAT/WEST LONG – LONG EQUAL TO OR GREATER THAN 100DEG
 *      S7530/W17000 – 7W570
 *  SOUTH LAT/EAST LONG – LONG LESS THAN 100 DEG
 *      S5030/E02000 – S5020
 *  SOUTH LAT/EAST LONG – LONG EQUAL TO OR GREATER THAN 100 DEG
 *      S75S0/E15000 – 7S550
 *
 *  EXCEPTIONS:  POINTS LEADING UP TO OCEANIC (UNNAMED POINTS):
 *    USE THE LAT DEG AND MIN FOLLOWED BY LAT
 *      N6046 W09000 – 6046N
 *      N6145/W08900 – 6145N
 *
 * FIELD TYPE: A/N
 *
 * ALLOWED VALUES:
 * 1ST POSITION:  COMBINATIONS OF LETTERS A-Z AND NUMBERS 0-9
 *  SUBSEQUENT POSITIONS:  COMBINATIONS OF LETTERS A-Z, NUMBERS 0-9, AND TRAILING SPACES.
 *
 * SOURCE: HOST NATION PUBLICATION OR DOD ORIGINATED
 *
 * INTENDED USE:
 * THE WAYPOINT TABLE IS THE ONLY TABLE THAT USES WPT_IDENT AS A KEY FIELD.  THE WAYPOINT KEY FIELDS (WPT_IDENT, WPT_COUNTRY) MUST EXIST IN THE WPT.TXT BEFORE ASSOCIATED IN OTHER RECORDS.  IN ORDER FOR A WAYPOINT TO BE ASSOCIATED WITH WPT1_IDENT OR WPT2_IDENT IN THE ATS RECORD IT MUST HAVE A USAGE CODE IN (H,L,B).
 *
 * PER DAFIF LOGIC RULES FOR MULTIPLE TABLES THAT USE NAVAIDS AS WAYPOINTS (INCLUDING ATS AND TERMINALS), A WAYPOINT WILL BE CO-LOCATED WITH A NAVAID. THESE WAYPOINTS ARE IDENTIFIED BY A 'Y' IN THE WPT.WPT_NAV_FLAG FIELD. THESE WAYPOINTS ARE CREATED BY NGA AND ARE NOT SOURCED FROM ANSP. THESE CO-LOCATED WAYPOINTS ARE DATABASE REFERENCES ONLY AND SHOULD NOT BE USED FOR NAVIGATION.
 */
public final class WaypointIdentifierWptIdent extends TrimmableString {
  @Override
  public int maxFieldLength() {
    return 5;
  }

  @Override
  public int fieldCode() {
    return 339;
  }

  @Override
  public String regex() {
    return "(([A-Z0-9]([A-Z0-9\\-]{0,4})?)?)";
  }
}