name: boogie
image: "repo.codev.mitre.org/idaass-docker/tdp/boogie-rest:latest"
imagePullSecrets: [ kubernetes-codev-pull ]
resources:
  cpu: 500m
  memory: 2Gi
  cpuLimit: 2000m
  memoryLimit: 4Gi
  storageClassName: efs-auto-provisioned
  storageResources: 300Mi
  replicas: 2
ingress:
  enabled: false
  host: 'boogie.streaming.cre.gov.aws.mitre.org'
deployment:
  annotations:
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
autoscaling:
  enable: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  scaleUpStabilizationWindowSeconds: 60
arinc:
  watchDirectory: '/data/arinc'
  filePattern: '.*dat'
cleanup:
  watchDirectory: false