---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boogie-rest
  namespace: tfm-analytics
  labels:
    app: boogie-rest
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: boogie-rest
  template:
    metadata:
      labels:
        app: boogie-rest
    spec:
      imagePullSecrets:
        - name: artifactory-image-pull-codev
      containers:
        - name: boogie-rest
          # Use the image built from the release version of the boogie software in the prod deployment
          image: repo.codev.mitre.org/idaass-docker/tdp/boogie-rest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: boogie-rest-config
          resources:
            requests:
              cpu: 200m
              memory: 5Gi
            limits:
              cpu: 400m
              memory: 10Gi
          volumeMounts:
            - name: boogie-arinc-db
              mountPath: /data/db/arinc
      # Claim to a volume which we assume will have a loaded cycle of procedure data in it
      volumes:
        - name: boogie-arinc-db
          persistentVolumeClaim:
            claimName: boogie-arinc-db