---
apiVersion: v1
kind: Service
metadata:
  name: boogie-rest
  namespace: tfm-analytics
spec:
  selector:
    app: boogie-rest
  ports:
    - name: rest-port
      protocol: TCP
      port: 8087
      targetPort: 8087
  clusterIP: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: boogie-rest
  namespace: tfm-analytics
spec:
  # The routes spec determines where on the EPIC cluster (and under what name) the app will be deployed - this hostname should be resolvable in the browser
  host: boogie-rest.apps.epic-osc.mitre.org
  to:
    kind: Service
    name: boogie-rest
    weight: 100
  port:
    targetPort: 8087
  tls:
    termination: edge
  wildcardPolicy: None