name: lido-integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Integration Test Data
        uses: actions/checkout@v4
        with:
          lfs: true
          repository: 'mitre-tdp/boogie-test'
          ssh-key: ${{ secrets.BOOGIE_TESTS_PRIVATE_KEYS }}
          ref: main
          path: ./boogie-arinc/src/test/resources

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Show Working directory
        run: ls ./boogie-arinc/src/test/resources

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew lido-integration
