name: publish-maven-central.yml
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to use'
        required: true
        type: string

env:
  VERSION: ${{ github.event.inputs.tag }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
#      - name: Publish packages to local staging directory
#        run: |
#          ./gradlew -Dmaven.repo.local=${{ github.workspace }}/boogie-core/target/staging-deploy/ :boogie-core:publishToMavenLocal -Pversion=${{ env.VERSION }}
#      - name: List staging directory contents
#        run: |
#          ls -la ${{ github.workspace }}
#          ls -la ${{ github.workspace }}/boogie-core/target/staging-deploy/org/mitre/boogie/*/*
#      - name: Debug version
#        run: |
#          echo "Version: ${{ env.VERSION }}"
      - name: Publish package to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_PUBLIC_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          BOOGIE_RELEASE_VERSION: ${{ env.VERSION }}
        run: |
          echo "Using version: ${{ env.VERSION }}"
          ./gradlew :boogie-util:publishToMavenCentral