name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to use'
        required: true
        type: string

env:
  VERSION: ${{ github.event.inputs.tag }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish packages to local staging directory
        run: |
          ./gradlew -Dmaven.repo.local=${{ github.workspace }}/build/staging-deploy/ publishToMavenLocal -Pversion=${{ env.VERSION }}
          
          ./gradlew -Dmaven.repo.local=${{ github.workspace }}/build/staging-deploy/ :boogie-arinc:publishToMavenLocal -Pversion=${{ env.VERSION }}
      - name: List staging directory contents
        run: |
          ls -la ${{ github.workspace }}
          ls -la ${{ github.workspace }}/build/staging-deploy/org/mitre/boogie/*/*
      - name: Debug version
        run: |
          echo "Version: ${{ env.VERSION }}"
      - name: Publish package to Maven Central
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOOGIE_RELEASE_VERSION: ${{ env.VERSION }}
        run: |
          echo "Using version: ${{ env.VERSION }}"
          ./gradlew jreleaserDeploy \
            --no-configuration-cache \
            -DaltDeploymentRepository=local::file:${{ github.workspace }}/build/staging-deploy/ \
            -Djreleaser.stage.release.enabled=true \
            -Djreleaser.project.version=${{ env.VERSION }}