name: Release

on:
  workflow_dispatch:

jobs:
  tag-release:
    name: Tag Library Version
    uses: mitre-actions/paved-roads/.github/workflows/tag-library-release.yaml@main
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}

  publish:
    name: Publish and Release
    needs: [tag-release]
    uses: mitre-actions/paved-roads/.github/workflows/publish-library.yaml@main
    secrets: inherit
    with:
      tag: ${{ needs.tag-release.outputs.new_tag }}
      branch: ${{ github.ref_name }}
      java-distribution: corretto
      java-version: 17