name: Release
on: [ workflow_dispatch ]
jobs:
  publish-release-image:
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: echo ::save-state name=RELEASE_VERSION::$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
      - name: Release Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: idaass-docker/tdp/boogie-rest
          username: ${{ secrets.CODEV_NAME_IDAASS_DEVELOPERS }}
          password: ${{ secrets.CODEV_TOKEN_IDAASS_DEVELOPERS }}
          registry: ${{ secrets.CODEV_URL }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
          buildargs: MAVEN_USER=${{ secrets.CODEV_NAME_IDAASS_USERS }},MAVEN_PASSWORD=${{ secrets.CODEV_TOKEN_IDAASS_USERS }}
