name: Commit Check and Release Candidate

# Commit checks and RC deployment run on all changes to trunk and all changes
# to PR branches, unless the PR is in draft
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

# when the action runs on a pull request trigger, then github.ref will be e.g. refs/pull/421/merge, so this gives us a consistent
# way to reference the branch name
env:
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

jobs:

  check:
    name: Build and Check Source
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mitre-actions/setup-gradle@v1
        with:
          java-distribution: corretto
          java-version: 11
          caasd-plugin-repo-username: ${{ secrets.CODEV_NAME_IDAASS_USERS }}
          caasd-plugin-repo-password: ${{ secrets.CODEV_TOKEN_IDAASS_USERS }}

      - name: Run Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check